### ISSUE TITLE
Woocommerce products not showing. Display a 404 error.

### ISSUE THREAD

**Issue by johnlmccurdy** [woocommerce/woocommerce#14481]
### EXPLANATION OF THE ISSUE

I have my site running on the salient theme (completely updated to 8.0.15) running on Woocommerce v3.0.3 and the products are there in the woocommerce backend, they are there in the SQL database, and all the permalink settings are correct. However when you view the product page on the site, it shows a 404 error.

So far I have tried everything to fix it, including turning off all forms of caching plugin, turned off the theme and used the standard wordpress 2017 theme. I have turned off all plugins except woocommerce and the payment gateway stripe, but nothing works.

The site is hosted on godaddy, on a shared hosting package.

Interestingly, I have the same set up for another site, but which is hosted elsewhere and I can see the products just fine.

It can’t be the hosting causing the issue can it? If so, is there a known solution?

### SYSTEM STATUS

<details>
``
### WordPress Environment ###

Home URL: https://www.discovergrandprix.com
Site URL: https://www.discovergrandprix.com
WC Version: 3.0.3
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.25
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: -1
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.33
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.3
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (46) ###

Distance - Hotel to Track: by John McCurdy – 1.0
Facebook Page Box: by John McCurdy – 1.0
F1 Next race: by John McCurdy – 1.0.
Mid Article Sign Up: by John McCurdy. – 1.0.
Advanced Recent Posts: by Eugene Holin – 0.6.14
Contact Form 7 MailChimp Extension: by Renzo Johnson – 0.4.43
Contact Form 7: by Takayuki Miyoshi – 4.7
Disqus Comment System: by Disqus  – 2.87
Duplicate Post: by Enrico Battocchi – 3.2
Instant Articles for WP: by Automattic
Dekode
Facebook – 3.3.3

Google XML Sitemaps: by Arne Brachhold – 4.0.8
Complete Analytics Optimization Suite (CAOS): by Daan van den Bergh – 1.44
Insert Headers and Footers: by WPBeginner – 1.4.2
Salient Visual Composer: by Michael M - WPBakery.com | Modified by ThemeNectar – 5.0.1
MailChimp for WooCommerce: by MailChimp – 1.1.1
MailChimp: by MailChimp – 1.5.7
Mapplic: by sekler – 4.1
Mashshare - Social Networks Add-On: by René Hermenau – 2.4.2
Mashshare Share Buttons: by René Hermenau – 3.4.1
Medium: by A Medium Corporation – 1.4.0
P3 (Plugin Performance Profiler): by GoDaddy.com – 1.5.3.9
PixelYourSite: by PixelYourSite – 5.0.2
WooCommerce Product Filter-Null24.Net: by Mihajlovic Nenad – 5.8.4
Printful Integration for WooCommerce: by Printful – 1.2.7
Publish to Apple News: by Alley Interactive – 1.2.5
Really Simple SSL: by Rogier Lankhorst – 2.5.11
Recent Posts Widget Extended: by Satrya – 0.9.9.6
Recent Posts Widget With Thumbnails: by Martin Stehle – 5.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Social Count Plus: by Claudio Sanches – 3.3.5
SumoMe: by SumoMe – 1.25
Tawk.to Live Chat: by Tawkto – 0.2.5
Weather App: by John McCurdy – 1.0
Woocommerce Variations Table - Grid: by Spyros Vlachopoulos – 1.3.4
WooCommerce Cart Reports: by WPBackOffice – 1.1.8 – 1.1.13 is available
WooCommerce Save & Share Cart - NULL24.NET: by cxThemes – 2.10
WooCommerce Stripe Gateway: by WooCommerce – 3.1.6
WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
Woocommerce Product Tabs: by Nilambar Sharma – 1.1
WooCommerce: by Automattic – 3.0.3
Yoast SEO: by Team Yoast – 4.6
WP All Export Pro: by Soflyy – 1.4.5
WP All Import Pro: by Soflyy – 4.3.0
WP Rocket | Shared By Themes24x7.com: by WP Rocket – 2.8.7
WP Smush: by WPMU DEV – 2.6.2
WP All Import - WooCommerce Add-On Pro: by Soflyy – 2.3.5

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #6638 - /shop/
Basket: #164 - /cart/
Checkout: #165 - /checkout/
My account: #166 - /my-account/

### Theme ###

Name: Salient
Version: 8.0.15
Author URL: http://themenectar.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
Go to settings > permalinks and save. Then clear caches.

I'll need a screenshot of permalink settings if it doesn't correct.

**Comment by mikejolley** [comment]
@johnlmccurdy done it yet?

**Comment by johnlmccurdy** [comment]
Sorry, got caught on the phone and I was also waiting for ten minutes for the cache clearing to "take effect". 

No change sadly. See screen shots.

![screencapture-discovergrandprix-product-2017-austrian-grand-prix-formula-1-tickets-1492512394724](https://cloud.githubusercontent.com/assets/27724965/25127216/04e63a46-242d-11e7-89d4-a35b5a4a7190.png)

![screencapture-discovergrandprix-wp-admin-options-permalink-php-1492512444787](https://cloud.githubusercontent.com/assets/27724965/25127233/107ffaa4-242d-11e7-96d6-bfbed100e9d0.png)

**Comment by mikejolley** [comment]
Can you do a test with WC extensions off, and visual composer off.

Also - WooCommerce Product Filter-Null24.Net: by Mihajlovic Nenad – 5.8.4 - I assume this is a 'free' nulled plugins site. This is a terribly bad idea - you do realise plugins on those sites can be edited by malicious users to add unsafe code to your site?

**Comment by johnlmccurdy** [comment]
Ok, I have de-activated all woocommerce related plugins and also visual composer. I get the same 404 result.

Also, no I didn't know about Null24 being malicious plugins. I honestly thought that they were simply a place to download deprecated versions... Thanks for the heads up.

**Comment by mikejolley** [comment]
I'm not certain that will be malicious, but you need to be cautious if not getting plugins from the author.

After de-activating things, resave permalinks. The flush of permalinks is important.

**Comment by johnlmccurdy** [comment]
I have done that already. I re-saved the permlinks, and then cleared all cache. I still got the 404.

**Comment by mikejolley** [comment]
Does setting the permalink base for products to something else work?

**Comment by johnlmccurdy** [comment]
Moving the permalink to the https://www.discovergrandprix.com/shop/sample-product/ base does actually work, but now all my incoming links won't work (or will they?)

**Comment by mikejolley** [comment]
No they won't. It looks like something is conflicting with the /product/ base. I cannot tell what however; I'd usually expect it to be a plugin or theme, but you'd need to do trial and error. You should also check there are no non-wordpress rules in your .htaccess file.

**Comment by johnlmccurdy** [comment]
Ok, I don't really know what I am looking for in that file, but please see the contents below. Does anything stand out?

`# BEGIN WP Rocket v2.8.7
# Use UTF-8 encoding for anything served text/plain or text/html
AddDefaultCharset UTF-8
# Force UTF-8 for a number of file formats
<IfModule mod_mime.c>
AddCharset UTF-8 .atom .css .js .json .rss .vtt .xml
</IfModule>

# FileETag None is not enough for every server.
<IfModule mod_headers.c>
Header unset ETag
</IfModule>

# Since we’re sending far-future expires, we don’t need ETags for static content.
# developer.yahoo.com/performance/rules.html#etags
FileETag None

# Send CORS headers if browsers request them; enabled by default for images.
<IfModule mod_setenvif.c>
<IfModule mod_headers.c>
# mod_headers, y u no match by Content-Type?!
<FilesMatch "\.(cur|gif|png|jpe?g|svgz?|ico|webp)$">
SetEnvIf Origin ":" IS_CORS
Header set Access-Control-Allow-Origin "*" env=IS_CORS
</FilesMatch>
</IfModule>
</IfModule>

# Allow access to web fonts from all domains.
<FilesMatch "\.(eot|otf|tt[cf]|woff2?)$">
<IfModule mod_headers.c>
Header set Access-Control-Allow-Origin "*"
</IfModule>
</FilesMatch>

<IfModule mod_alias.c>
<FilesMatch "\.(html|htm|rtf|rtx|txt|xsd|xsl|xml)$">
<IfModule mod_headers.c>
Header set X-Powered-By "WP Rocket/2.8.7"
Header unset Pragma
Header append Cache-Control "public"
Header unset Last-Modified
</IfModule>
</FilesMatch>

<FilesMatch "\.(css|htc|js|asf|asx|wax|wmv|wmx|avi|bmp|class|divx|doc|docx|eot|exe|gif|gz|gzip|ico|jpg|jpeg|jpe|json|mdb|mid|midi|mov|qt|mp3|m4a|mp4|m4v|mpeg|mpg|mpe|mpp|otf|odb|odc|odf|odg|odp|ods|odt|ogg|pdf|png|pot|pps|ppt|pptx|ra|ram|svg|svgz|swf|tar|tif|tiff|ttf|ttc|wav|wma|wri|xla|xls|xlsx|xlt|xlw|zip)$">
<IfModule mod_headers.c>
Header unset Pragma
Header append Cache-Control "public"
</IfModule>
</FilesMatch>
</IfModule>

# Expires headers (for better cache control)
<IfModule mod_expires.c>
ExpiresActive on

# Perhaps better to whitelist expires rules? Perhaps.
ExpiresDefault                          "access plus 1 month"

# cache.appcache needs re-requests in FF 3.6 (thanks Remy ~Introducing HTML5)
ExpiresByType text/cache-manifest       "access plus 0 seconds"

# Your document html
ExpiresByType text/html                 "access plus 0 seconds"

# Data
ExpiresByType text/xml                  "access plus 0 seconds"
ExpiresByType application/xml           "access plus 0 seconds"
ExpiresByType application/json          "access plus 0 seconds"

# Feed
ExpiresByType application/rss+xml       "access plus 1 hour"
ExpiresByType application/atom+xml      "access plus 1 hour"

# Favicon (cannot be renamed)
ExpiresByType image/x-icon              "access plus 1 week"

# Media: images, video, audio
ExpiresByType image/gif                 "access plus 1 month"
ExpiresByType image/png                 "access plus 1 month"
ExpiresByType image/jpeg                "access plus 1 month"
ExpiresByType video/ogg                 "access plus 1 month"
ExpiresByType audio/ogg                 "access plus 1 month"
ExpiresByType video/mp4                 "access plus 1 month"
ExpiresByType video/webm                "access plus 1 month"

# HTC files  (css3pie)
ExpiresByType text/x-component          "access plus 1 month"

# Webfonts
ExpiresByType application/x-font-ttf    "access plus 1 month"
ExpiresByType font/opentype             "access plus 1 month"
ExpiresByType application/x-font-woff   "access plus 1 month"
ExpiresByType application/x-font-woff2  "access plus 1 month"
ExpiresByType image/svg+xml             "access plus 1 month"
ExpiresByType application/vnd.ms-fontobject "access plus 1 month"

# CSS and JavaScript
ExpiresByType text/css                  "access plus 1 year"
ExpiresByType application/javascript    "access plus 1 year"

</IfModule>

# Gzip compression
<IfModule mod_deflate.c>
# Active compression
SetOutputFilter DEFLATE
# Force deflate for mangled headers
<IfModule mod_setenvif.c>
<IfModule mod_headers.c>
SetEnvIfNoCase ^(Accept-EncodXng|X-cept-Encoding|X{15}|~{15}|-{15})$ ^((gzip|deflate)\s*,?\s*)+|[X~-]{4,13}$ HAVE_Accept-Encoding
RequestHeader append Accept-Encoding "gzip,deflate" env=HAVE_Accept-Encoding
# Don’t compress images and other uncompressible content
SetEnvIfNoCase Request_URI \
\.(?:gif|jpe?g|png|rar|zip|exe|flv|mov|wma|mp3|avi|swf|mp?g)$ no-gzip dont-vary
</IfModule>
</IfModule>

# Compress all output labeled with one of the following MIME-types
<IfModule mod_filter.c>
AddOutputFilterByType DEFLATE application/atom+xml \
		                          application/javascript \
		                          application/json \
		                          application/rss+xml \
		                          application/vnd.ms-fontobject \
		                          application/x-font-ttf \
		                          application/xhtml+xml \
		                          application/xml \
		                          font/opentype \
		                          image/svg+xml \
		                          image/x-icon \
		                          text/css \
		                          text/html \
		                          text/plain \
		                          text/x-component \
		                          text/xml
</IfModule>
<IfModule mod_headers.c>
Header append Vary: Accept-Encoding
</IfModule>
</IfModule>

<IfModule mod_mime.c>
AddType text/html .html_gzip
AddEncoding gzip .html_gzip
</IfModule>
<IfModule mod_setenvif.c>
SetEnvIfNoCase Request_URI \.html_gzip$ no-gzip
</IfModule>

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{HTTPS} on [OR]
RewriteCond %{SERVER_PORT} ^443$ [OR]
RewriteCond %{HTTP:X-Forwarded-Proto} https
RewriteRule .* - [E=WPR_SSL:-https]
RewriteCond %{HTTP:Accept-Encoding} gzip
RewriteRule .* - [E=WPR_ENC:_gzip]
RewriteCond %{REQUEST_METHOD} GET
RewriteCond %{QUERY_STRING} =""
RewriteCond %{HTTP:Cookie} !(wordpress_logged_in_|wp-postpass_|wptouch_switch_toggle|comment_author_|comment_author_email_) [NC]
RewriteCond %{REQUEST_URI} !^(/checkout/(.*)|/cart/|/my-account/(.*))$ [NC]
RewriteCond %{HTTP_USER_AGENT} !^(facebookexternalhit).* [NC]
RewriteCond "%{DOCUMENT_ROOT}/wp-content/cache/wp-rocket/%{HTTP_HOST}%{REQUEST_URI}/index%{ENV:WPR_SSL}.html%{ENV:WPR_ENC}" -f
RewriteRule .* "/wp-content/cache/wp-rocket/%{HTTP_HOST}%{REQUEST_URI}/index%{ENV:WPR_SSL}.html%{ENV:WPR_ENC}" [L]
</IfModule>
# END WP Rocket

# ----------------------------------------------------------------------
# CORS-enabled images (@crossorigin)
# ----------------------------------------------------------------------
# Send CORS headers if browsers request them; enabled by default for images.
# developer.mozilla.org/en/CORS_Enabled_Image
# blog.chromium.org/2011/07/using-cross-domain-images-in-webgl-and.html
# hacks.mozilla.org/2011/11/using-cors-to-load-webgl-textures-from-cross-domain-images/
# wiki.mozilla.org/Security/Reviews/crossoriginAttribute
<IfModule mod_setenvif.c>
  <IfModule mod_headers.c>
    # mod_headers, y u no match by Content-Type?!
    <FilesMatch "\.(gif|png|jpe?g|svg|svgz|ico|webp)$">
      SetEnvIf Origin ":" IS_CORS
      Header set Access-Control-Allow-Origin "*" env=IS_CORS
    </FilesMatch>
  </IfModule>
</IfModule>
# ----------------------------------------------------------------------
# Webfont access
# ----------------------------------------------------------------------
# Allow access from all domains for webfonts.
# Alternatively you could only whitelist your
# subdomains like "subdomain.example.com".
<IfModule mod_headers.c>
  <FilesMatch "\.(ttf|ttc|otf|eot|woff|font.css|css)$">
    Header set Access-Control-Allow-Origin "*"
  </FilesMatch>
</IfModule>
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress
`

**Comment by mikejolley** [comment]
Don't see anything too concerning there. Just caching rules.

**Comment by johnlmccurdy** [comment]
Ok, so are there any other suggestions for now?

**Comment by mikejolley** [comment]
I don't think you've tried my previous suggestions yet.

**Comment by mikejolley** [comment]
^ That was to check plugins/theme for conflicts. Given the permalinks work with a different base, this is almost certainly a conflict rather than a WC bug. It could be a plugin, conflicting post type, even a page/post with the same name 'product'. I'm closing this as it's specific to your site but let us know what you find.

**Comment by johnlmccurdy** [comment]
I solved this thanks to your last comment. It was an attribute that also had the 'product' name. This therefore caused the conflict and created the 404 error. It's worth noting though that although the error existed previously, when we were running the versions of woocommerce before 3.0.3, that no error actually presented at the front end. So I guess, you guys have changed something which will no longer allow conflicts like this.

Thanks for the responsive help though.

**Comment by RonalddeRooij** [comment]
Thank You! I had the same problem and it had something to do with a attribute called 'Product'. Changing the slug of the attribute solved my issue.

**Comment by uhi** [comment]
Thanks also from my side, had the same problem - changing permalinks settings, saving and changing back did the trick ...

**Comment by thistempname** [comment]
The solution that worked for me:
1) Unselect Product Photos In Products
2) Save / Refresh Settings | Permalinks
3) Select Corresponding Product Photos In Products
4) Save / Refresh Settings | Permalinks

**Comment by WPprodigy** [comment]
@mikejolley Just came across another site where there was a global attribute with a slug of `product`, causing the product base permalink to not work.

Anything we could do here to make the conflict a bit more visible? Perhaps introduce a priority as well that gives priority to the product base over attribute slug if possible.

**Comment by mikejolley** [comment]
@WPprodigy Pretty sure WP controls the order permalinks work; we don't register those manually.

**Comment by VincentLoy** [comment]
Had the same issue after upgrading Debian 8 to 9 and php 5 to 7.

I feel stupid but : simply `mod_rewrite` [that was not enabled](https://wordpress.stackexchange.com/questions/311828/woocommerce-product-page-404-not-found) :)

I leave it here to remind people to check mod_rewrite

**Comment by lima2001** [comment]
I’ve had this issue for 4 days! Yes!! It was a attribute called products I deleted and all single product pages displaying again!! whats strange is that I haven’t added any new attributes for over a month before the issue surfaced.

**Comment by srijanc** [comment]
I am getting a Server 503 error while accessing Product tab under woo-commerce.

**Comment by WPprodigy** [comment]
@srijanc That seems entirely unrelated to this thread. Please open up a new support issue here: https://wordpress.org/support/plugin/woocommerce/. 

If you can, check your PHP error logs as there is likely a fatal error happening. More info: https://wordpress.org/support/topic/how-to-debug-issues-after-updates

**Comment by carlosromanxyz** [comment]
You need consider don't have two or more slug with same name

For example:

I've 
'producto' (base)
'producto' (attribute)

Changing slug (or attribute's name and slug), issue is solved.

**Comment by omargian** [comment]
Hello... I also have the bad request error 404. The funny thing is that I'm using GET method and that work fine but when I want to update or create new products using PUT  I have the error. I already read all documentation of woocommerce for update a product. But still not working for me any help is very appreciate.

**Comment by pokhiii** [comment]
[This comment](https://github.com/woocommerce/woocommerce/issues/14481#issuecomment-296688883) is a lifesaver! Thank you!!
