### ISSUE TITLE
WC3 Import / Export problem with i18n header column

### ISSUE THREAD

**Issue by Stephan256** [woocommerce/woocommerce#19596]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Use Export function in Products admin page : "Variable Products" and "Variations"
2. Use Import function in Products admin page 
3. No correct matching due localization (French for me)

## Expected/actual behavior

Hi Woocommerce team,

It’s a very simple problem : the column header generate for export use the translation so after in importation matching not correctly work.
By example col-header : **“metas: _ref2”** becomes in french **“Métasnbsp;: _ref2”**, the same for attributes,…
Then during the import nothing works properly...

You know, for us, the rest of the world, who speaks another language, with special characters : a lot of programming problem exists with extended characters but they are rarely tested on your side.
And i can’t remove translation .mo just for this problem, isn’t it ?

Thank you in advance.

See also :
https://wordpress.org/support/topic/wc3-import-export-problem-with-i18n-header-column/#post-10141447

## WordPress Environment

WP 4.9.4 (French .mo)
WC 3.3.4 (French .mo)

<details>
`
### WordPress Environment ###

Home URL: https://vps488054.ovh.net
Site URL: https://vps488054.ovh.net
WC Version: 3.3.4
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: fr_FR

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30-0+deb8u1
PHP Post Max Size: 55 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - Nous recommandons MySQL version 5.6 minimum. Voir : Exigences de WordPress
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Taille totale de la base de données: 83.64MB
Taille de la base de données: 58.47MB
Taille de l’index: 25.17MB
wp_woocommerce_sessions: Donnée : 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Donnée : 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Donnée : 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Donnée : 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Donnée : 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Donnée : 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Donnée : 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Donnée : 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Donnée : 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Donnée : 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Donnée : 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Donnée : 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Donnée : 0.02MB + Index: 0.03MB
wp_woocommerce_log: Donnée : 0.02MB + Index: 0.02MB
wp_commentmeta: Donnée : 0.02MB + Index: 0.03MB
wp_comments: Donnée : 0.02MB + Index: 0.09MB
wp_links: Donnée : 0.02MB + Index: 0.02MB
wp_options: Donnée : 1.25MB + Index: 0.06MB
wp_postmeta: Donnée : 46.58MB + Index: 18.03MB
wp_posts: Donnée : 8.52MB + Index: 4.81MB
wp_termmeta: Donnée : 0.08MB + Index: 0.06MB
wp_terms: Donnée : 0.05MB + Index: 0.03MB
wp_term_relationships: Donnée : 1.52MB + Index: 1.52MB
wp_term_taxonomy: Donnée : 0.05MB + Index: 0.03MB
wp_usermeta: Donnée : 0.02MB + Index: 0.03MB
wp_users: Donnée : 0.02MB + Index: 0.05MB
wp_wc_download_log: Donnée : 0.02MB + Index: 0.03MB
wp_wc_webhooks: Donnée : 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 14827
customize_changeset: 4
nav_menu_item: 10
page: 19
post: 1
product: 6050
product_variation: 35
shop_coupon: 1
shop_order: 3
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Query Monitor: par John Blackbourn – 2.17.0
PW WooCommerce Bulk Edit: par Pimwick
WooCommerce: par Automattic – 3.3.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
outofstock (outofstock)

### WC Pages ###

Base boutique: #1 - /?page_id=1
Panier: #2 - /?page_id=2
Commande: #3 - /?page_id=3
Mon compte: #4 - /?page_id=4
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: *****
Version: 1.0.0
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.2.8
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by claudiosanches** [comment]
> You know, for us, the rest of the world, who speaks another language, with special characters : a lot of programming problem exists with extended characters

Good that we have people that speak Portuguese, Spanish and other languages developing WooCommerce.
I myself developed the importer/exported and already handing issues with translations and testing in Portuguese, so you can bet that we are looking for the rest of the world too.

So, since this is clear now, I tested in Portuguese and there is no problem like that, for me your problem seems related to the translations to French, probably because someone included `&nbsp;` that means a space before `:`, therefore you should fix it into French translation in here:

https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/fr/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=4575991&filters%5Btranslation_id%5D=50379328

Someone should be able to approve this translations, I advise you to correct all extra `&nbsp;` that you can find in that translation.
Good luck.

**Comment by Stephan256** [comment]
Thank you Claudio !

 

I have do all the suggestion of the columns header in translate.wordpress.org. I hope thez understand for while (I can’t find where add comment of this change)

 

However sometime translate use special char like &rsquo; for ‘ 
Maybe the problem persist

 

Regards

 

Stephan

 

 

De : Claudio Sanches [mailto:notifications@github.com] 
Envoyé : mercredi 4 avril 2018 20:13
À : woocommerce/woocommerce
Cc : Stephan R; Author
Objet : Re: [woocommerce/woocommerce] WC3 Import / Export problem with i18n header column (#19596)

 

You know, for us, the rest of the world, who speaks another language, with special characters : a lot of programming problem exists with extended characters

Good that we have people that speak Portuguese, Spanish and other languages developing WooCommerce.
I myself developed the importer/exported and already handing issues with translations and testing in Portuguese, so you can bet that we are looking for the rest of the world too.

So, since this is clear now, I tested in Portuguese and there is no problem like that, for me your problem seems related to the translations to French, probably because someone included &nbsp; that means a space before :, therefore you should fix it into French translation in here:

https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/fr/default?filters%5Bstatus%5D=either <https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/fr/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=4575991&filters%5Btranslation_id%5D=50379328> &filters%5Boriginal_id%5D=4575991&filters%5Btranslation_id%5D=50379328

Someone should be able to approve this translations, I advise you to correct all extra &nbsp; that you can find in that translation.
Good luck.
