### ISSUE TITLE
Wordpress Update 5.02 broke the orders tab

### ISSUE THREAD

**Issue by poly-media** [woocommerce/woocommerce#22271]
hey,
one of my sites auto updated to 5.02 this night and the orders tab (only the all tab) is not showing any orders. Was working fine before update. Running latest woocommerce & wordpress.

Seems like more people having the same issue: https://woocommerce.com/posts/woocommerce-and-wordpress-5-0/ 
(comment: "Daniel Ellis
December 20, 2018	at 4:22 am	#
Hi
The website update to 5.02
And in woocomnerce orders
All orders is blank and tab called mine is blank some if the others still appears to be there , I think a technical problem needing updating fast
I have 2 others with same issue all ready")

<img width="1487" alt="screenshot" src="https://user-images.githubusercontent.com/34577934/50261479-01098d80-040d-11e9-999e-9bc1e8725e9f.png">

**Comment by adelineyaw** [comment]
Issue seen via chat 8942288-hc (follow up via 1658282-zen)

**Comment by orhanfernandes** [comment]
Issue seen via chat 8943986-hc (followed up via 1658327-zen) and 8943726-hc

**Comment by orhanfernandes** [comment]
Issue seen via 7596898-hc

**Comment by cmbaldwin** [comment]
Seconding this as well, also happening on my instance (in Japanese). On the "processing" tab, and other specific order type exploration tabs, it shows up.
![screenshot_2018-12-20 funabiki online wordpress](https://user-images.githubusercontent.com/7152249/50264633-db0cd900-045e-11e9-9078-c5cdf55bb9f9.png)

**Comment by SiR-DanieL** [comment]
One more at 8945012-hc

**Comment by AashikP** [comment]
Also reported in 5309012-hc. Follow-up at 1658433-zen

**Comment by tamarazuk** [comment]
I've run across this on several merchant sites as well. Confirmed locally that the issue appears right after updating WP to 5.0.2. Filtering by individual statuses does allow me to view orders however.

**Comment by pento** [comment]
Here's a workaround for this issue, which you can use until a fix is released:

```php
function fix_request_query_args_for_woocommerce( $query_args ) {
	if ( isset( $query_args['post_status'] ) && empty( $query_args['post_status'] ) ) {
		unset( $query_args['post_status'] );
	}
	return $query_args;
}
add_filter( 'request', 'fix_request_query_args_for_woocommerce', 1, 1 );
```

**Comment by dougaitken** [comment]
Adding any of my interactions here:
8946131-hc

**Comment by whitetornado** [comment]
where to add or change?? facing the same issue

**Comment by SiR-DanieL** [comment]
@whitetornado you need to add the code in `wp-content/themes/your-child-theme-name/functions.php` at the end of the file.

**Comment by amirhoseindavat** [comment]
> Here's a workaround for this issue, which you can use until a fix is released:
> 
> ```
> function fix_request_query_args_for_woocommerce( $query_args ) {
> 	if ( isset( $query_args['post_status'] ) && empty( $query_args['post_status'] ) ) {
> 		unset( $query_args['post_status'] );
> 	}
> 	return $query_args;
> }
> add_filter( 'request', 'fix_request_query_args_for_woocommerce', 1, 1 );
> ```
Thank you man 👍🏻

**Comment by vietanhdev** [comment]
![image](https://user-images.githubusercontent.com/18329471/50275995-642e0b00-0473-11e9-9107-92babc75559d.png)
It also happened with my site.

**Comment by donalirl** [comment]
Another #8406393-hc

**Comment by rodrigoprimo** [comment]
See PR #22273. It would be great if we could get some people to test it as we plan to release a new version of WC as soon as possible.

**Comment by JohnnyXP64** [comment]
any possible release time for this guys?

**Comment by vimes1984** [comment]
I'm experincing this problem aswell guys +1 on a fix

**Comment by franckadil** [comment]
Hi,

We Thanks to Pento and David Commarmond

We have crafted a plugin that fixes the issue, while waiting for a solution from the devs at WooCommerce 🙂

Here is the plugin:
https://github.com/junglewp/WooFix

WordPress Peace Keepers

**Comment by fernandotellado** [comment]
The new released version 3.5.3 claim to solve the orders issue but breaks the block editor too :(

<img src="https://i.imgur.com/meEbxOx.png" />

The error copied is this one:

`TypeError: Cannot read property 'select' of undefined
    at https://testu.sgedu.site/wp-includes/js/dist/editor.min.js:55:271508
    at n.value (https://testu.sgedu.site/wp-includes/js/dist/data.min.js:1:14919)
    at new n (https://testu.sgedu.site/wp-includes/js/dist/data.min.js:1:14614)
    at zf (https://testu.sgedu.site/wp-includes/js/dist/vendor/react-dom.min.js:69:258)
    at Mf (https://testu.sgedu.site/wp-includes/js/dist/vendor/react-dom.min.js:87:4)
    at ph (https://testu.sgedu.site/wp-includes/js/dist/vendor/react-dom.min.js:98:474)
    at eg (https://testu.sgedu.site/wp-includes/js/dist/vendor/react-dom.min.js:125:307)
    at fg (https://testu.sgedu.site/wp-includes/js/dist/vendor/react-dom.min.js:126:168)
    at wc (https://testu.sgedu.site/wp-includes/js/dist/vendor/react-dom.min.js:138:237)
    at fa (https://testu.sgedu.site/wp-includes/js/dist/vendor/react-dom.min.js:137:115)`

**Comment by rodrigoprimo** [comment]
@fernandotellado, if you believe this problem is caused by WooCommerce core, could you please open another issue using the [bug report template](https://github.com/woocommerce/woocommerce/issues/new?template=Bug_report.md) providing all the details to reproduce the issue? On a first look, this seems unrelated to the 3.5.3 fix, but we don't have enough information to be sure. I quickly tested editing posts and pages in my local environment, and the block editor is working.

**Comment by fernandotellado** [comment]
Done!

https://github.com/woocommerce/woocommerce/issues/22279

**Comment by letsallhelp** [comment]
Hi gang, Just jumping in here. WooCommerce just released an updated that fixed the order display issue however if your also have WooCommerce Subscriptions like I do the error is still there - Guessing they missed this??

**Comment by ProMarpe** [comment]
Hi I updated to Wordpress 5.0.2 recently and as we know, orders disappeared. Woocommerce came out with an update to 3.5.3 and I did that, only weird thing is all of my December orders are missing now. I tried de-activating plugins and activating them again one by one but to no avail. Anyone knows the reason why?

**Comment by makeonlineshop** [comment]
Hello,
Can you please tell me how to avoid this problem ?
I haven't updated anything yet as it is so clear that new (often useless) updates always bring problems.
Thank you.

**Comment by webthread** [comment]
Seems this issue still happens with WC Subscriptions activated. Seems a long time to leave things as it's now April.

**Comment by rodrigoprimo** [comment]
@webthread, this issue tracker is used exclusively for WooCommerce core. If you believe the problem you are experiencing is related to core, could you please open another issue detailing the steps to reproduce it? If instead, you believe the problem is caused by WooCommerce Subscriptions, please contact Woocommerce.com support: http://woocommerce.com/contact-us/

**Comment by mombrea** [comment]
@davidcommarmond just came across this myself, one minor update to the version check since the latest version of WordPress has increased to make it >= :

```
if(version_compare(get_option( 'woocommerce_version' ),"3.5.2","<=") && version_compare(get_bloginfo( 'version' ),"5.0.2",">=") ){
    function fix_request_query_args_for_woocommerce( $query_args ) {
        if ( isset( $query_args['post_status'] ) && empty( $query_args['post_status'] ) ) {
                unset( $query_args['post_status'] );
        }
        return $query_args;
    }
    add_filter( 'request', 'fix_request_query_args_for_woocommerce', 1, 1 );
}
```
