### ISSUE TITLE
WooCommerce 3.5.4 and WordPress 5.0.3 REST API: Image upload broken (woocommerce_product_invalid_image_id)

### ISSUE THREAD

**Issue by blasto333** [woocommerce/woocommerce#22557]
I am using v2 of the REST API. This code worked fine on an older version of WordPress and WooCommerce. I cannot upload an image to a product.

The first error after the upgrade I got was:

    array (
      'code' => 'woocommerce_product_image_upload_error',
      'message' => 'Invalid image: Sorry, this file type is not permitted for security reasons.',
      'data' => 
      array (
        'status' => 400,
      ),

Resolved by adding following in `wp-config.php` to the bottom of the file:

    define('ALLOW_UNFILTERED_UPLOADS', true);

The 2nd error I cannot figure out. The image won't upload and leaves a ghost image where it was uploaded.

**Code**

    <?php
    require __DIR__ . '/vendor/autoload.php';
    
    use Automattic\WooCommerce\Client;
    
    $woocommerce = new Client(
        'http://localhost/wordpress', 
        'ck_44b92c00ea35e6cc59c89c29051bf67c22e0df3a', 
        'cs_dd833592a1ef7a00a82c1711fd455db2e4c5bd15',
        [
            'wp_api' => true,
            'version' => 'wc/v2',
        ]
    );
    
    $data['create'][] = array(
        'name' => 'TEST',
        'regular_price' => '4.50',
        'description' => 'TEST DESC',
        'type' => 'simple',
        'images' => array(
            array(
                'alt' => '',
                'name' => '',
                'src' => 'https://via.placeholder.com/350x150',
                'position' => 0,
            ),
        )
    );
    
    
    $response = $woocommerce->post('products/batch',$data);
    $headers = $woocommerce->http->getResponse()->getHeaders();
    var_dump($headers);
    var_dump($response);

**Response Data**

    array(13) {
      ["Date"]=>
      string(29) "Thu, 24 Jan 2019 18:22:16 GMT"
      ["Server"]=>
      string(6) "Apache"
      ["X-Powered-By"]=>
      string(9) "PHP/7.2.1"
      ["X-Robots-Tag"]=>
      string(7) "noindex"
      ["Link"]=>
      string(63) "<http://localhost/wordpress/wp-json/>; rel="https://api.w.org/""
      ["X-Content-Type-Options"]=>
      string(7) "nosniff"
      ["Access-Control-Expose-Headers"]=>
      string(27) "X-WP-Total, X-WP-TotalPages"
      ["Access-Control-Allow-Headers"]=>
      string(27) "Authorization, Content-Type"
      ["Expires"]=>
      string(29) "Wed, 11 Jan 1984 05:00:00 GMT"
      ["Cache-Control"]=>
      string(36) "no-cache, must-revalidate, max-age=0"
      ["Allow"]=>
      string(16) "POST, PUT, PATCH"
      ["Content-Length"]=>
      string(3) "139"
      ["Content-Type"]=>
      string(31) "application/json; charset=UTF-8"
    }
    array(1) {
      ["create"]=>
      array(1) {
        [0]=>
        array(2) {
          ["id"]=>
          int(0)
          ["error"]=>
          array(3) {
            ["code"]=>
            string(36) "woocommerce_product_invalid_image_id"
            ["message"]=>
            string(27) "#82 is an invalid image ID."
            ["data"]=>
            array(1) {
              ["status"]=>
              int(400)
            }
          }
        }
      }
    }

**Comment by rrennick** [comment]
Can you post your system status report?

**Comment by dustinpitcher** [comment]
@rrennick I am also having this issue. So I'll include my system status report. Same as the OP, I was getting the "not permitted for security reasons" error, then when I allowed unfiltered uploads I'm getting the "Invalid Image ID" error.

I should note that I do have quite a few plugins and a custom theme but I use this API integration to publish products to my site almost daily and the only thing to change since it was working was an upgrade to WC. 

Here is the info you requested:

REQUEST BODY:

`
{"name":"NBS DPMS LR-308 Extended Easy Pull Takedown Pin - Stainless Steel","enable_html_description":true,"type":"simple","status":"draft","virtual":false,"sku":"3115","sale_price":"11.9500","regular_price":"11.9500","tax_status":"none","manage_stock":true,"stock_quantity":30,"weight":"0.0000","description":"<p>The Stainless Steel NBS Easy Pull Takedown Pin (Rear) for DPMS Pattern LR-308 Rifles features an extended head making this an ideal addition for anyone who needs to be able to quickly separate the upper and lower receiver. Commonly used in restricted states along with an AR Maglock or other kind of magazine removal compliance hardware.</p>
<ul>
<li>Stainless Steel</li>
<li>American Made</li>
<li>Backed by NBS Limited Lifetime Warranty</li>
</ul>","images":[{"src":"https://inventory.dearsystems.com/Product/Download/fec7fb89-2017-464a-afcc-5dd549b966b6","position":0},{"src":"https://inventory.dearsystems.com/Product/Download/c5510741-27c0-4618-8b98-9c51361dba75"},{"src":"https://inventory.dearsystems.com/Product/Download/d5542faa-be15-4b77-8a1d-5b9c8ec9c8a3"}],"attributes":[]}
`

RESPONSE HEADERS: 

`
{
    "Set-Cookie": "yith_wcwl_products=%5B%5D; expires=Wed, 30-Jan-2019 212704 GMT; Max-Age=0; path=\/",
    "Content-Type": "application\/json; charset=UTF-8",
    "X-Robots-Tag": "noindex",
    "Link": "<https\/\/ar15discounts.com\/wp-json\/>; rel="https\/\/api.w.org\/"",
    "X-Content-Type-Options": "nosniff",
    "Access-Control-Expose-Headers": "X-WP-Total, X-WP-TotalPages",
    "Access-Control-Allow-Headers": "Authorization, Content-Type",
    "Expires": "Wed, 11 Jan 1984 050000 GMT",
    "Cache-Control": "no-cache, must-revalidate, max-age=0",
    "X-QM-overview-time_taken": "0.7874",
    "X-QM-overview-time_usage": "0.1% of 600s limit",
    "X-QM-overview-memory": "60,404 kB",
    "X-QM-overview-memory_usage": "5.8% of 1,048,576 kB limit",
    "X-QM-php_errors-error-count": "1",
    "X-QM-php_errors-error-1": "{"type""notice","message""Undefined index type","file""wp-admin\/includes\/file.php","line"810,"stack"["_wp_handle_upload()","wp_handle_sideload()","wc_rest_upload_image_from_url()","WC_REST_Products_V2_Controller->set_product_images()","WC_REST_Products_V2_Controller->prepare_object_for_database()","WC_REST_CRUD_Controller->save_object()","WC_REST_CRUD_Controller->create_item()","WP_REST_Server->dispatch()","WP_REST_Server->serve_request()","rest_api_loaded()","do_action_ref_array('parse_request')","WP->parse_request()","WP->main()","wp()"],"component""Plugin woocommerce"}",
    "Allow": "GET, POST"
}
`

RESPONSE BODY: 

`
{
    "data": {
        "code": "woocommerce_product_invalid_image_id",
        "message": "#128321 is an invalid image ID.",
        "data": {
            "status": 400
        }
    },
    "headers": {
        "Allow": "GET, POST"
    },
    "status": 400
}
`

SYSTEM REPORT:

`
### WordPress Environment ###

Home URL: https://ar15discounts.com
Site URL: https://ar15discounts.com
WC Version: 3.5.4
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.37 (Unix) OpenSSL/1.1.0g
PHP Version: 7.3.1
PHP Post Max Size: 1 GB
PHP Time Limit: 600
PHP Max Input Vars: 5000
cURL Version: 7.58.0
OpenSSL/1.1.0g

SUHOSIN Installed: –
MySQL Version: 5.7.25-0ubuntu0.18.04.2-log
Max Upload Size: 512 MB
Default Timezone is UTC: ❌ Default timezone is America/Los_Angeles - it should be UTC
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.4
WC Database Prefix: wpmqd_
MaxMind GeoIP Database: ✔
Total Database Size: 6595.79MB
Database Data Size: 6041.38MB
Database Index Size: 554.41MB
wpmqd_woocommerce_sessions: Data: 11.09MB + Index: 0.25MB
wpmqd_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wpmqd_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wpmqd_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wpmqd_woocommerce_order_items: Data: 6.33MB + Index: 2.99MB
wpmqd_woocommerce_order_itemmeta: Data: 30.02MB + Index: 22.17MB
wpmqd_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wpmqd_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wpmqd_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wpmqd_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wpmqd_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wpmqd_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wpmqd_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wpmqd_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wpmqd_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB
wpmqd_bv_dynamic_sync: Data: 8.02MB + Index: 0.00MB
wpmqd_bv_ip_store: Data: 0.00MB + Index: 0.00MB
wpmqd_commentmeta: Data: 1.12MB + Index: 0.80MB
wpmqd_comments: Data: 8.31MB + Index: 3.85MB
wpmqd_facetwp_index: Data: 0.89MB + Index: 0.41MB
wpmqd_failed_jobs: Data: 0.00MB + Index: 0.00MB
wpmqd_lecm_rewrite: Data: 2.52MB + Index: 0.00MB
wpmqd_lecsm_import: Data: 5.52MB + Index: 4.55MB
wpmqd_lecsm_recent: Data: 0.02MB + Index: 0.00MB
wpmqd_lecsm_update: Data: 0.02MB + Index: 0.02MB
wpmqd_lecsm_user: Data: 0.02MB + Index: 0.00MB
wpmqd_links: Data: 0.00MB + Index: 0.00MB
wpmqd_mailchimp_carts: Data: 0.00MB + Index: 0.00MB
wpmqd_mc4wp_log: Data: 0.02MB + Index: 0.00MB
wpmqd_micro_revisions: Data: 1.52MB + Index: 0.00MB
wpmqd_options: Data: 19.64MB + Index: 2.46MB
wpmqd_phone_orders_log: Data: 0.00MB + Index: 0.00MB
wpmqd_postmeta: Data: 318.18MB + Index: 436.38MB
wpmqd_posts: Data: 5553.71MB + Index: 24.10MB
wpmqd_queue: Data: 0.00MB + Index: 0.00MB
wpmqd_redirection_404: Data: 23.52MB + Index: 7.23MB
wpmqd_redirection_groups: Data: 0.00MB + Index: 0.00MB
wpmqd_redirection_items: Data: 0.10MB + Index: 0.07MB
wpmqd_redirection_logs: Data: 3.23MB + Index: 0.83MB
wpmqd_scalability_pro_profiling: Data: 0.00MB + Index: 0.00MB
wpmqd_sm_advanced_search_temp: Data: 0.02MB + Index: 0.00MB
wpmqd_social_users: Data: 0.00MB + Index: 0.00MB
wpmqd_swp_cf: Data: 0.00MB + Index: 0.00MB
wpmqd_swp_index: Data: 6.17MB + Index: 4.09MB
wpmqd_swp_log: Data: 0.00MB + Index: 0.01MB
wpmqd_swp_tax: Data: 0.11MB + Index: 0.11MB
wpmqd_swp_terms: Data: 0.30MB + Index: 0.35MB
wpmqd_termmeta: Data: 0.06MB + Index: 0.05MB
wpmqd_terms: Data: 0.03MB + Index: 0.11MB
wpmqd_term_relationships: Data: 5.28MB + Index: 17.66MB
wpmqd_term_taxonomy: Data: 0.10MB + Index: 0.10MB
wpmqd_usermeta: Data: 32.88MB + Index: 22.91MB
wpmqd_users: Data: 2.36MB + Index: 2.69MB
wpmqd_wc_download_log: Data: 0.00MB + Index: 0.00MB
wpmqd_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wpmqd_yith_wcwl: Data: 0.01MB + Index: 0.01MB
wpmqd_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB
wpmqd_yoast_seo_links: Data: 0.11MB + Index: 0.02MB
wpmqd_yoast_seo_meta: Data: 0.11MB + Index: 0.12MB

### Post Type Counts ###

acf-field: 10
acf-field-group: 3
ar_promo: 2
attachment: 5814
blocks: 10
customize_changeset: 8
custom_css: 1
gp_elements: 1
jetpack_migration: 2
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 62
oembed_cache: 1
page: 36
post: 6
postman_sent_mail: 250
product: 1565
product_variation: 715
revision: 29
saswp: 2
scheduled-action: 6488
shop_coupon: 709
shop_order: 26768
shop_order_refund: 296
sidebar: 2
wafs: 1
wcam: 2
wcpf_item: 5
wcpf_project: 1
wc_product_table: 6
wp-rest-api-log: 79948
wpcf7_contact_form: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (49) ###

Query Monitor: by John Blackbourn & contributors – 3.2.2
Advanced Custom Fields PRO: by Elliot Condon – 5.7.9
Auto Infinite Scroll: by Dave Hilditch – 1.17 – Not tested with the active version of WooCommerce
WordPress Backup & Security Plugin - BlogVault: by Backup by BlogVault – 1.84
Cache-Control: by Geeky Software – 2.2.3
Connexity Tracking Code: by Dustin Pitcher – 0.1 – Not tested with the active version of WooCommerce
Error Log Monitor: by Janis Elsts – 1.6.3
FacetWP - Conditional Logic: by FacetWP
LLC – 1.3.0

FacetWP - Flatsome integration: by FacetWP
LLC – 0.4.2

FacetWP: by FacetWP
LLC – 3.3.0

Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 5.3.7
WooCommerce Search Plugin by Instant Search +: by Fast Simon Inc – 1.11.12
Kadence WooCommerce Email Designer: by Kadence Themes – 1.1.4
MailChimp for WordPress: by ibericode – 4.3.3
Manage Notification E-mails: by Virgial Berveling – 1.4.1
MailChimp for WordPress - Premium: by ibericode – 4.5.5
Microthemer: by Themeover – 5.5.3.0
Nextend Social Login: by Nextendweb – 3.0.17
Nextend Social Login Pro Addon: by Nextendweb – 3.0.15
Phone Orders for WooCommerce (Pro): by AlgolPlus – 3.2.2
Post SMTP: by Jason Hendriks
Yehuda Hassine – 1.9.5

Redirection: by John Godley – 3.7.2
Redis Object Cache: by Till Krüss – 1.4.1
Scalability Pro: by Dave Hilditch – 4.43 – Not tested with the active version of WooCommerce
Smart Manager: by StoreApps – 4.0.4
Stamped.io Product Reviews: by Stamped.io – 1.9.6
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.19
Temporary Login Without Password: by StoreApps – 1.5.14
Product Feed PRO for WooCommerce: by AdTribes.io – 4.3.8
WooCommerce Variation Swatches: by Emran Ahmed – 1.0.52
Advanced Messages for WooCommerce: by Jeroen Sormani – 1.3.3 – Not tested with the active version of WooCommerce
WooCommerce Composite Products: by SomewhereWarm – 3.15.0
WooCommerce Composite Products Modifications: by SomewhereWarm – 1.0 – 1.0.0 is available – Not tested with the active version of WooCommerce
WooCommerce Authorize.Net CIM Gateway: by SkyVerge – 2.10.2
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.12.2
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.27
WooCommerce Smart Coupons: by StoreApps – 3.9.1
WooCommerce Waitlist: by WooCommerce – 1.8.9
WooCommerce: by Automattic – 3.5.4
WooSidebars: by WooCommerce – 1.4.5
Yoast SEO: by Team Yoast – 9.5
WP 404 Auto Redirect to Similar Post: by hwk-fr – 1.0.2
REST API Log: by Pete Nelson – 1.6.6
WP Rocket | No Cache for Admins: by WP Rocket Support Team –
WP Rocket: by WP Media – 3.2.4
Yoast SEO: WooCommerce: by Team Yoast – 9.5
YITH WooCommerce Brands Add-on Premium: by YITH – 1.3.0
YITH WooCommerce Recently Viewed Products Premium: by YITH – 1.4.6
YITH WooCommerce Wishlist: by YITH – 2.2.7

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: AR15Discounts Theme
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.7.2
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
ar15discounts-theme/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
ar15discounts-theme/woocommerce/single-product/meta.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php


### Composite Products ###

Database Version: 3.15.0
Template Overrides: –

### Authorize.Net CIM ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off
Webhooks Enabled: ✔
`

**Comment by dustinpitcher** [comment]
@rrennick Thanks for taking the time to respond to this. 

I realize that the OP appears to be uploading an image without an extension but that is not the case with me. If you look at my request and then hit that image source url (https://inventory.dearsystems.com/Product/Download/fec7fb89-2017-464a-afcc-5dd549b966b6) in the browser, you'll see it is just a standard JPG file (DSCF1292-2.jpg) which I can upload directly into the WP-ADMIN no problem. 

I can see how that might be a problem if the REST controller is evaluating the url itself and not the file, but I'm not sure because since this change was made back in 5.02 I can confirm that I was able to update / publish thousands of products using the same request and image url described above even after that change. It is only within the last few days that it stopped working. 

Further, I have installed and activated the old disable-real-mime-check plugin and that did not work. As mentioned above I even defined "ALLOW_UNFILTERED_UPLOADS = true" and it is still not functioning properly.

Given what I mentioned above, any more info would be greatly appreciated.

In the mean time I'll talk to our vendor and point them in the direction of this ticket so they evaluate if changes need to be made on their end.  

Also, @blasto333 have you made progress on your end that might be helpful?

**Comment by smagnetize** [comment]
One of our clients resolved this issue by reverting back to WooCommerce 3.5.3, he didn't mention anything about also reverting to a previous version of WordPress.

**Comment by rrennick** [comment]
I'll re-open this and see if I can reproduce the second half of the original description. The first message in the description is the WP core message media validation per my screenshot.

`'message' => 'Invalid image: Sorry, this file type is not permitted for security reasons.',`

**Comment by dustinpitcher** [comment]
Just wanted to stop by and confirm that a roll-back of Woocommerce to 3.5.3 also worked to resolve my issue.

**Comment by mikejolley** [comment]
Working request:

```
{
	"name": "TEST",
	"regular_price": "4.50",
	"description": "TESTDESC",
	"type": "simple",
	"images": [
		{
			"alt": "",
			"name": "",
			"src": "https://via.placeholder.com/350x150.png",
			"position": 0
		}
	]
}
```

Broken Request:

```
{
	"name": "TEST",
	"regular_price": "4.50",
	"description": "TESTDESC",
	"type": "simple",
	"images": [
		{
			"alt": "",
			"name": "",
			"src": "https://via.placeholder.com/350x150",
			"position": 0
		}
	]
}
```

WP Core validates the extension. In this case, the image filename has none which causes the error. https://core.trac.wordpress.org/browser/tags/5.0.3/src/wp-admin/includes/file.php#L796

Adding the `.png` extension to the URL works around the issue.

**Comment by claudiosanches** [comment]
This may open your installation for security issues, so be careful.

> Resolved by adding following in wp-config.php to the bottom of the file:
> define('ALLOW_UNFILTERED_UPLOADS', true);

**Comment by mikejolley** [comment]
2nd notice in OP ("is an invalid image ID.") is correct. The _file_ is uploaded, but it has no extension and is not recognised by WP as an image. `wp_attachment_is_image` is false.

This is also fixed by providing an extension (see my last comment).

Thanks

**Comment by wywarren** [comment]
Currently running into this same problem 3.8.1. Uploading via media library works, tried with client's url (contained file extension of .jpg) and also tried uploading it to S3 public bucket and using that url and still the same result.

```
{
    "create": [
        {
            "id": 0,
            "error": {
                "code": "woocommerce_product_invalid_image_id",
                "message": "#111869 不是合法的圖片編號。",
                "data": {
                    "status": 400
                }
            }
        }
    ]
}
```

**Comment by adeelulrahman** [comment]
I am having the same issue of `# is an invalid image ID.` 

I want to upload Google Photos or Google Drive photos but the problem is that they do not take an extension. I am doing this for a client and cannot roll-back WooCommerce to 3.5.3. 

Any suggestions for me?

**Comment by boctulus** [comment]
Same problem here in 2021 !
