### ISSUE TITLE
Cannot filter OUT OF STOCK after update to 3.6.0 or 3.6.1

### ISSUE THREAD

**Issue by walkinverse** [woocommerce/woocommerce#23416]
After upgrade, I was no longer able to see a list of out of stock items in the admin screen of the products.  When I clicked filter list and choose Out of Stock, then click Filter, it returned all products except for out of stock products.  The product displayed all had a quantity of >= 10 on all sites where I upgraded.  Same issue on different domains.

Once I rolled back the woocommerce plugin to 3.5.7 or 3.5.8 everything once again worked properly.  It only happens if you upgrade to the current version of woocommerce.

**Comment by peterfabian** [comment]
Hi,

this is probably caused by the new lookup table (which speeds up working with meta data) not being generated correctly.

Please check WooCommerce > Status > Action Scheduler for Pending jobs. All jobs can be executed manually if they are not picked up by CRON automatically (Run link appears on each line after mouse over).

If you see any of the jobs in Failed category, please post the error here (unless it's been already reported).

If the Action Scheduler jobs finished but you still see this problem, please try to regenerate the loopkup table. Look for “Product lookup tables” in “WooCommerce” > “Status” > “Tools” and click in “Regenerate”, this should fix it.

**Comment by mikejolley** [comment]
Added to the FAQ https://github.com/woocommerce/woocommerce/wiki/3.6.x-notes-FAQ#i-am-having-issues-sortingsearching-by-sku-after-the-update

**Comment by walkinverse** [comment]
The issue is not closed.  Just went through all the directions above and the error still persists.  This did not resolve. I have no pending jobs and everything has run as expected.

https://www.dropbox.com/s/kw87wdrmuauoxbr/Screenshot%202019-04-23%2020.37.02.png?dl=0

https://www.dropbox.com/s/rem5zh9yalsa9a6/Screenshot%202019-04-23%2020.39.53.png?dl=0

You cannot filter for out of stock as it does not work.
