### ISSUE TITLE
PayPal Standard: Simultaneous IPN and PDT responses *sometimes* reduce stock twice

### ISSUE THREAD

**Issue by melek** [woocommerce/woocommerce#24387]
**Describe the bug**
When PDT is enabled on a PayPal Business Account, it is possible for WooCommerce to get both IPN and PDT verification of a payment. Sometimes (but not always), this causes a duplicate stock reduction on stock-managed items. This error occured 3 times for a product we sold 258 of over this last weekend.

**To Reproduce**
1. Have PayPal Standard enabled, with PDT enabled on the linked business account
2. Sell an item through the gateway
3. Sometimes, see error - about 1% of the time in our case.

**Screenshots**
(The same managed-stock product was in each screenshot)
Both IPN and PDT are processed, and stock is reduced twice: 
![image](https://user-images.githubusercontent.com/220149/62890918-562a4480-bcf9-11e9-980e-595a56acb40b.png)

Both IPN and PDT are processed, and stock is only reduced once (notes in different order): 
![image](https://user-images.githubusercontent.com/220149/62893547-ba500700-bcff-11e9-97eb-df9f2f87e12f.png)

**Expected behavior**
I expect stock to be reduced only once.

**Discussion**
I see that this issue has repeatedly come up in the past, most plainly in [#15951](https://github.com/woocommerce/woocommerce/issues/15951), but they are all closed and ultimately point to a solution in pull [#20030](https://github.com/woocommerce/woocommerce/pull/20030). That pull request may have fixed the problem most of the time, or lay the groundwork for a solution, but we still experience this problem on our site.

There is a closed forum post on the WooCommerce plug-in repository that says "You should only use IPN or PDT, never both. This is why there are two notifications of a complete payment and why PayPal is reducing stock twice.". ([link](https://wordpress.org/support/topic/woocommerce-reduces-stock-twice/))

But disabling one is not a desirable solution; PayPal's documentation says that PDT is meant to be instantaneous but only fires once, and IPN fires until it gets a receipt but has a lagged response. They even suggest carefully implementing both to get both reliability for the database and instant confirmation for the customer ([source](https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNPDTAnAlternativetoIPN/))

**WordPress Environment**
<details>

```

### WordPress Environment ###

WordPress address (URL): https://buttonpoetry.com
Site address (URL): https://buttonpoetry.com
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.20-2+ubuntu18.04.1+deb.sury.org+1
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1c

SUHOSIN Installed: –
MySQL Version: 5.7.26-29-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: yxn_
MaxMind GeoIP Database: ✔
Total Database Size: 2116.21MB
Database Data Size: 1600.58MB
Database Index Size: 515.63MB
yxn_woocommerce_sessions: Data: 5.02MB + Index: 0.08MB
yxn_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
yxn_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
yxn_woocommerce_downloadable_product_permissions: Data: 2.52MB + Index: 6.92MB
yxn_woocommerce_order_items: Data: 9.52MB + Index: 4.52MB
yxn_woocommerce_order_itemmeta: Data: 356.66MB + Index: 72.22MB
yxn_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
yxn_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
yxn_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
yxn_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
yxn_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
yxn_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
yxn_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
yxn_woocommerce_log: Data: 0.02MB + Index: 0.02MB
yxn_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB
yxn_atum_order_items: Data: 0.02MB + Index: 0.02MB
yxn_atum_product_data: Data: 0.02MB + Index: 0.05MB
yxn_commentmeta: Data: 3.52MB + Index: 4.03MB
yxn_comments: Data: 57.59MB + Index: 43.09MB
yxn_duplicator: Data: 0.02MB + Index: 0.00MB
yxn_hw_blocks: Data: 0.23MB + Index: 0.09MB
yxn_hw_layout_meta: Data: 0.02MB + Index: 0.02MB
yxn_hw_snapshots: Data: 71.52MB + Index: 0.02MB
yxn_hw_wrappers: Data: 0.06MB + Index: 0.02MB
yxn_links: Data: 0.02MB + Index: 0.02MB
yxn_mc4wp_log: Data: 10.52MB + Index: 0.00MB
yxn_ms_snippets: Data: 0.02MB + Index: 0.00MB
yxn_options: Data: 2.50MB + Index: 0.20MB
yxn_plugin_notes_plus: Data: 0.02MB + Index: 0.00MB
yxn_postmeta: Data: 257.81MB + Index: 263.78MB
yxn_posts: Data: 30.55MB + Index: 19.06MB
yxn_prli_clicks: Data: 0.02MB + Index: 0.19MB
yxn_prli_groups: Data: 0.02MB + Index: 0.02MB
yxn_prli_links: Data: 0.02MB + Index: 0.16MB
yxn_prli_link_metas: Data: 0.02MB + Index: 0.03MB
yxn_pum_subscribers: Data: 0.02MB + Index: 0.06MB
yxn_sm_advanced_search_temp: Data: 0.02MB + Index: 0.00MB
yxn_snippets: Data: 0.06MB + Index: 0.00MB
yxn_stream: Data: 5.02MB + Index: 10.22MB
yxn_stream_meta: Data: 13.02MB + Index: 22.20MB
yxn_termmeta: Data: 0.02MB + Index: 0.03MB
yxn_terms: Data: 0.16MB + Index: 0.17MB
yxn_term_relationships: Data: 2.52MB + Index: 1.50MB
yxn_term_taxonomy: Data: 0.16MB + Index: 0.22MB
yxn_usermeta: Data: 40.58MB + Index: 40.13MB
yxn_users: Data: 2.52MB + Index: 2.42MB
yxn_vtprd_purchase_log: Data: 0.02MB + Index: 0.02MB
yxn_vtprd_purchase_log_product: Data: 0.02MB + Index: 0.02MB
yxn_vtprd_purchase_log_product_rule: Data: 0.02MB + Index: 0.02MB
yxn_wcch_page_history: Data: 698.00MB + Index: 0.00MB
yxn_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB
yxn_wc_admin_notes: Data: 0.02MB + Index: 0.00MB
yxn_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB
yxn_wc_customer_lookup: Data: 5.52MB + Index: 5.03MB
yxn_wc_download_log: Data: 1.52MB + Index: 0.69MB
yxn_wc_order_coupon_lookup: Data: 1.52MB + Index: 0.72MB
yxn_wc_order_product_lookup: Data: 9.52MB + Index: 10.06MB
yxn_wc_order_stats: Data: 6.52MB + Index: 6.55MB
yxn_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB
yxn_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
yxn_wc_webhooks: Data: 0.02MB + Index: 0.02MB
yxn_woocommerce_bundled_itemmeta: Data: 0.08MB + Index: 0.06MB
yxn_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
yxn_yoast_seo_links: Data: 1.52MB + Index: 0.47MB
yxn_yoast_seo_meta: Data: 3.52MB + Index: 0.00MB
yxn_zendesk_woo_auto_create_ticket: Data: 0.02MB + Index: 0.00MB
yxn_zendesk_woo_custom_form: Data: 0.02MB + Index: 0.00MB
yxn_zendesk_woo_log_user: Data: 0.02MB + Index: 0.00MB
yxn_zendesk_woo_user_mapping: Data: 0.02MB + Index: 0.00MB
yxn_zendesk_woo_webhook_db: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

amn_mi-lite: 1
amn_om: 1
attachment: 1928
bp_feature_slide: 14
customize_changeset: 6
custom_css: 2
mc4wp-form: 6
nav_menu_item: 59
omapi: 3
page: 67
popup: 2
popup_theme: 7
post: 1515
postman_sent_mail: 350
product: 75
product_variation: 131
pys_event: 2
pys_fb_event: 1
revision: 56
scheduled-action: 6114
shop_coupon: 325
shop_order: 52947
shop_order_refund: 246
shop_webhook: 1
wc_stamps_label: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (49) ###

Akismet Anti-Spam: by Automattic – 4.1.2
Beeketing For WooCommerce: by Beeketing – 3.8.15
Classic Editor: by WordPress Contributors – 1.5
Code Snippets: by Shea Bunge – 2.13.3
Google AdSense: by Google – 1.2.1
Hide WooCommerce Categories On Shop Page: by Matix Web Designers – 1.0.1 – Not tested with the active version of WooCommerce
Mailchimp for WordPress: by ibericode – 4.5.3
MailChimp for WordPress - Premium: by ibericode – 4.5.10
OptinMonster API: by OptinMonster Team – 1.7.0
Pinterest Verify: by Phil Derksen – 1.0.4
PixelYourSite PRO: by PixelYourSite – 7.2.0
Plugin Notes Plus: by Jamie Bergen – 1.2.0
Popup Maker: by WP Popup Maker – 1.8.10
Post SMTP: by Yehuda Hassine – 2.0.2
Product Catalog Feed Pro by PixelYourSite: by PixelYourSite – 4.0.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.1
Robot Ninja Helper: by Prospress Inc. – 1.11.0
Stream: by XWP – 3.4.1
Compress JPEG & PNG images: by TinyPNG – 3.2.0
Title Remover: by WPGurus – 1.2.1
TMSM WooCommerce Product Gift Wrap: by Nicolas Mollet – 1.1.2 – Not tested with the active version of WooCommerce
User Role Editor: by Vladimir Garagulya – 4.51.2
WooCommerce Better Customer List: by Blaze Concepts – 1.2.1
Woo Orders Date Range Filter: by TheWPexperts – 2.0.0
WooCommerce Admin: by WooCommerce – 0.16.0
WooCommerce Composite Products: by SomewhereWarm – 4.1.1 – 4.2.0 is available
WooCommerce Cost of Goods: by SkyVerge – 2.8.4 – 2.9.0 is available
WooCommerce Customer History: by Brian Richards – 1.2.1 – Not tested with the active version of WooCommerce
WooCommerce Authorize.Net Gateway: by SkyVerge – 3.0.5 – 3.0.6 is available
WooCommerce Grid / List toggle: by jameskoster – 1.2.1 – Not tested with the active version of WooCommerce
Advanced Order Export For WooCommerce (Pro): by AlgolPlus – 3.0.1
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.3.0
WooCommerce Print Invoices/Packing Lists: by SkyVerge – 3.6.7 – 3.7.0 is available
WooCommerce Pre-Orders: by WooCommerce – 1.5.16 – 1.5.17 is available
WooCommerce Product Bundles: by SomewhereWarm – 5.11.1 – 5.12.0 is available
WooCommerce USPS Shipping: by WooCommerce – 4.4.27 – 4.4.28 is available
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.28 – 4.1.29 is available
WooCommerce Shortcodes: by WooThemes
Claudio Sanches – 1.0.0 – Not tested with the active version of WooCommerce

WooCommerce Smart Coupons: by StoreApps – 4.0.8
WooCommerce - StampscomEndicia Integration: by Stamps.comEndicia – 2.0.0 – Not tested with the active version of WooCommerce
WooCommerce TM Extra Product Options: by themeComplete – 4.9.6
WooCommerce Wholesale Prices Premium: by Rymera Web Co – 1.16.8 – Not tested with the active version of WooCommerce
WooCommerce Wholesale Prices: by Rymera Web Co – 1.9
WooCommerce: by Automattic – 3.6.5 – 3.7.0 is available
Yoast SEO: by Team Yoast – 11.7 – Not tested with the active version of WooCommerce
WP Add Mime Types: by Kimiya Kitani – 2.4.0
WP Engine Content Performance: by WP Engine – 1.5.3+627.25f0b62
Yotpo Social Reviews for Woocommerce: by Yotpo – 1.1.8 – Not tested with the active version of WooCommerce
Zendesk Support for WordPress: by Zendesk – 1.7.3

### Inactive Plugins (4) ###

Advanced Order Export For WooCommerce: by AlgolPlus – 3.0.1
ATUM Inventory Management for WooCommerce: by Stock Management Labs™ – 1.6.0
JWT Authentication for WP-API: by Enrique Chavez – 1.2.6
WooCommerce Admin Bar Addition: by David Decker - DECKERWEB – 2.7.0 – Not tested with the active version of WooCommerce

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
install.php: install.php
object-cache.php: Memcached Redux

### Must Use Plugins (4) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.6.4
SSO: by Garth Mortensen
Mike Hansen – 0.1

Stop long comments: by WPEngine – 0.0.4
WP Engine System: by WP Engine – 3.2.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #88 - /shop/
Cart: #89 - /cart/
Checkout: #90 - /checkout/
My account: #91 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Button Theme
Version: 1.2.4
Author URL: https://buttonpoetry.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: /nas/content/live/buttonpoetry/wp-content/plugins/woocommerce-tm-extra-product-options/templates/cart/cart-item-data.php
Button-Theme/woocommerce/emails/admin-cancelled-order.php
Button-Theme/woocommerce/emails/admin-failed-order.php
Button-Theme/woocommerce/emails/customer-completed-order.php
Button-Theme/woocommerce/emails/email-downloads.php
Button-Theme/woocommerce/emails/plain/email-downloads.php
Button-Theme/woocommerce/order/order-downloads.php


### Composite Products ###

Database Version: 4.1.1
Template Overrides: –

### Product Bundles ###

Database Version: 5.11.1
Template Overrides: –

### Authorize.Net Credit Card ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off
Webhooks Enabled: ❌
						No signature key configured

### Action Scheduler ###

Complete: 6,091
Oldest: 2019-07-12 15:25:02 -0500
Newest: 2019-08-12 15:14:03 -0500

Pending: 3
Oldest: 2019-08-12 15:49:03 -0500
Newest: 2019-08-16 15:25:03 -0500

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 20
Oldest: 2019-06-06 11:01:38 -0500
Newest: 2019-06-25 19:04:40 -0500
```
</details>

**Comment by im1981** [comment]
Hello,

we are facing the same issue from time to time.

It´s very annoying, customer receives the email twice, the stock is reduced twice.

Should be finally fixed. 
Regards

**Comment by vedanshujain** [comment]
Related (and might already be fixed by) #24249

**Comment by im1981** [comment]
Hello @vedanshujain, 
thanks for quick response, in which version was this patch applied? 
Because i and @melek are using 3.6.5 still, did it came in 3.7.0?

Regards,
Ingo

**Comment by vedanshujain** [comment]
The above patch will be released with 3.8 soon.

**Comment by juliaamosova** [comment]
@melek can you please test WooCommerce 3.8 (in case you haven't tested yet) and let us know if the issue was fixed for you?

**Comment by ptvtpc** [comment]
I still have the same problem in WooCommerce version 3.8.1. Is there any fix for this yet???

**Comment by melek** [comment]
@juliaamosova 
I am sorry for the delay. We ended up migrating payments to PayPal Pro so I can't review our transactions to see if the problem went away (we worked around it by swapping payment gateways).

It mainly occurred at times of high sales volume on a production site, and I was not able to reproduce the original issue using PayPal sandbox at the time. Unfortunately, I'm not in a position to easily test this. Sorry!

**Comment by juliaamosova** [comment]
Hi @melek,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.

**Comment by mouligreenlaw** [comment]
This ticket might be the same issue and they are running WooCommerce 4.4.1:
3309165-zen

**Comment by AashikP** [comment]
Seeing a similar behavior in the latest version of WooCommerce (4.5.2) in 3342709-zen:

Only a single product was purchased:

![https://d.pr/i/y5R3nL+](https://d.pr/i/y5R3nL+)

But the stock was reduced twice:

![https://d.pr/i/Dcq5tm+](https://d.pr/i/Dcq5tm+)

cc @juliaamosova

**Comment by juliaamosova** [comment]
Reopening the issue due to recent comments.

**Comment by mkaschke** [comment]
Is there a workaround?

**Comment by sachvietus** [comment]
This fix works for me:

Leave that PDT field blank so it won’t delete the product twice via IPN then PDT. Normally IPN itself should be enough, don’t need PDT.


![6E926250-E90E-45B2-A3BF-7A5CE81A5A55](https://user-images.githubusercontent.com/65779876/94471204-5ea83d80-018e-11eb-9804-744c3fa6fa1b.jpeg)

**Comment by ontiuk** [comment]
Also getting this on a clients site running the latest Woocommerce: 4.5.2. Sporadic but certainly a lot higher than 1% of the time. Very frustrating.

**Comment by noelillinger** [comment]
Hey guys, 

I'm searching through the web for days already, asked developers of installed plugins to help me, because I thought it's their code issue, but in the end I need to figure out, that it has to be the problem, that is written down here for many months already. (no fix yet??) 

I have the same issue, PDT & IPN status is both triggered, which also sends out the confirmation email twice. Not only the confirmation email, but all the automation emails that are bound to the order status. 

In my case it is the -> Order status changed from Pending payment to Completed (Screenshot) which gets triggered twice after completed order. 
It happens in more than 50% of the cases and is so annoying already with complaining customers who received 4 emails after each + I have to change up all automations myself.

![image](https://user-images.githubusercontent.com/75263101/100627626-81d6a100-3327-11eb-8421-e006e2207497.png)

Please fix this issue as fast as even possible, is there a work around? As I read the only work around is deleting the PDT token, which I need for immidiate confirmation, so the customer can download their digital products. 

Noel

**Comment by jessLundie** [comment]
Also reported in 4020073-zen in the form of duplicate status changes triggering duplicate order confirmation emails that are bound to order status.

**Comment by nicholasjeberlin** [comment]
4712931-zen in the form of duplicate commission generation in combination with Product Vendors

**Comment by vbelolapotkov** [comment]
@woocommerce/quark sending this one to you for prioritization.
