### ISSUE TITLE
Product Blocks not Responnsive

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce#24444]
**Describe the bug**

On mobile, the  products block does not show  one product  per row, but multiple columns.

**To Reproduce**
1. Go to a new pae
2. Add a Hand-Picked product block
3. See error on mobile

**Screenshots**

![](http://d.wedj.at/6KvJq0+)
**Image Link**: http://d.wedj.at/6KvJq0+

**Expected behavior**

I'd expect to see a single column, maybe 2.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by Usmanakram123** [comment]
for this you need to do it writing code for responsive products block.

**Comment by Usmanakram123** [comment]
for this you need to do it by writing CSS code for responsive products block.

**Comment by vedanshujain** [comment]
I am not sure what should be the ideal expected behavior, because blocks allow you to explicitly set the number of columns, although I guess it makes sense to not honor that setting when the screen width is low.

**Comment by LevinMedia** [comment]
@SiR-DanieL thanks for the report! 

For the immediate issue at hand: I tested in storefront, and I'm seeing three columns on mobile as well... I _thought_ that storefront was supposed to have some kind of built in CSS overrides to reduce the number of columns on tablet and mobile, (it's currently maintaining whatever number of columns are specified in the block, at all screen sizes) so either my memory serves me incorrectly, or something has changed that's preventing that from happening. 

Now, some additional background: Long ago (January this year) we designed various methods for controlling the number of column that would display in a block. 

After a round of usability testing, ( p6riRB-3Ri-p2 ) we decided it would be best to give users explicit column control per device size, IE 6 columns on desktop 3 on tablet, 1 on mobile) 

At the same time folks in Gutenberg were having a very similar discussion. 

https://github.com/WordPress/gutenberg/issues/13363

Because of that we decided to hold off on final designs and implementation, as we thought it would be better if we let Gutenberg lead the way on it... we saw the value in those controls being standardized across all blocks that need similar functionality. 

However, seeing as it's now almost September, and there's no clear resolution for the issue noted above, I think we should press forward with our own implementation of these controls as soon as possible. If a viable solution lands in core, we can always update the blocks to use those patterns. 

cc @pmcpinto @jwold

**Comment by ajgw** [comment]
Is there a relation to my post at storefront hub?

https://github.com/woocommerce/storefront/issues/1197

**Comment by ajgw** [comment]
Hi @jwold 
I do not understand what the trouble is. If I create a block with latest blog posts (which is part of WordPress core) and select three columns, they get on mobile into one column. So support is there, you need to use it. Or am I wrong?

**Comment by daveloodts** [comment]
**The new blocks in WC 3.7 are not mobile-friendly.**
This is a screenshot op 3.6.5 for iphone x

![Schermafbeelding 2019-08-29 om 11 10 27](https://user-images.githubusercontent.com/7976627/63927768-a79f3700-ca4e-11e9-8976-16d142aa08bf.png)

This is a screenshot on 3.7, same block, same mobile

![Schermafbeelding 2019-08-29 om 11 11 28](https://user-images.githubusercontent.com/7976627/63927802-bab20700-ca4e-11e9-8d41-becf32628ad9.png)


The core column block also allows setting a number of columns, but IS mobile-friendly by shrinking it to 1 or 2 columns. Don't think we need an answer of 'write your own css'.
This is clearly a bug. 

In 3.6.5, it was fine all the way.

**Comment by jwold** [comment]
Thanks for the followup! Agreed that this looks like a bug in 3.7. Something to take a look at. Thanks!

**Comment by jokanane** [comment]
WC 3.6.5 had a file..:

https://github.com/woocommerce/woocommerce/blob/master/assets/css/woocommerce-smallscreen.scss

…that set 2 columns side by side on small screens, but the file’s gone now, and there does not seem to be anything for responsiveness in..:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/assets/css/style.scss

**Comment by mirmillo** [comment]
For those needing a quick, dirty & temporary fix... using the Storefront theme, in the Theme Customizer, add something like this to your Additional CSS.

```
@media only screen and (max-width: 600px) {
	.wc-block-grid.has-4-columns .wc-block-grid__product {
		flex: 1 0 100%;
    max-width: 100%; 
	}
}
```

**Comment by vedanshujain** [comment]
I am marking the milestone to 3.9, but ideally, we should fix this soon.

**Comment by daveloodts** [comment]
Really, in 3.9 ?? What is the fuzz then about blocks if you don't prioritize this fix. I'll bet there are complexer fixes then this, right.

**Comment by claudiosanches** [comment]
@daveloodts we changed our release circle, also we are close to release 3.8, and shouldn't take too long to release 3.9, like 2 or 3 months. Not to mention that if you are using the Products Blocks feature plugin you'll get any block related update before comes to WooCommerce core.

**Comment by daveloodts** [comment]
@claudiosanches that is incorrect. I just tried out your suggestion: installing WooCommerce Blocks plugin. And it's still not responsive... can't believe this, so easy to solve

**Comment by kloon** [comment]
@daveloodts I think Claudio was trying to let you know how the release cycle has changed. The blocks functionality is developed independently from WooCommerce core and by a different team, what Claudio is trying to tell you is that since we are sticking to a new timeline of releasing every 2-3 months you will have greater success in installing the blocks plugin and updating that as they release more frequent, meaning you will have the fixes sooner than 3.9.

Regarding the issue, I did discuss it with the blocks development team and they will take a look and revert with feedback. You can follow along with the product blocks development on their GitHub repository https://github.com/woocommerce/woocommerce-gutenberg-products-block
