### ISSUE TITLE
Overall rounding issue

### ISSUE THREAD

**Issue by nuvoPoint** [woocommerce/woocommerce#24975]
Hey,
after looking at the issue tracker ( #24784, #24633, #24619, #24540, #24184, #24084, #23916 ) and investigating the code, it's clear that there is a comprehensive underlying issue regarding rounding in WooCommerce.

It's definitely not the first time we encounter rounding issues and therefore we wanted to shed some light on this issue and how we normally would approach this.

1) The setting WooCommerce->Settings->"Number of decimals" should only be used as a display option and not the way it is right now where it's also used for internal calculations.

2) Don't round any data that's used for internal calculations. This will keep the precision as high as possible.

3) Don't round any data that's getting stored to the database. This will maintain a high precision.

As it is now wc_get_price_decimals is getting used for all sorts of rounding which is plainly wrong and needs to be refactored. We were about to do a pull request for this but after looking into the issue tracker and some of the already existing PR ( #24828, #24776, #24208 ) we would think it will be better to assist instead.

We would also like to know what the plan is from the core team regarding rounding?

**Comment by larssn** [comment]
I would like to extend this issue to also include the REST endpoints; namely, the REST endpoints should NOT round values based on the `Number of decimals` setting. Let me do that in my end, if I require it.

**Comment by nuvoPoint** [comment]
@larssn You can actually use the dp filter on the REST calls to get the decimal precision you want, but this requires that the data is not rounded before it's saved, otherwise you will get wrong data with desired decimal precision.
`class-wc-api-orders.php line 152`

**Comment by peterfabian** [comment]
Hi, 

the plan is to look into refactoring the tax calculations after we wrap up post 3.8 clean up and some security work. Apologies for the issues.

**Comment by larssn** [comment]
@peterfabian Since you explicitly mention tax calculations, I'd like to point out that rounding is general problem, not limited to tax calculations.

**Comment by larssn** [comment]
I see this was removed from the 3.9.0 milestone. When is it planned then? In my opinion it's a pretty critical issue that an e-commerce platform can't do math correctly.

**Comment by vedanshujain** [comment]
@larssn many of the linked issues are fixed and are included in 3.9. I will post an update in some time (maybe by tomorrow) about the current status.

**Comment by vedanshujain** [comment]
Thanks for linking these at one place. There have been a bunch of updates to fixes for rounding errors and lots of high impact issues linked here are already fixed and will be available in 3.9. 

> It's definitely not the first time we encounter rounding issues and therefore we wanted to shed some light on this issue and how we normally would approach this.
> 
>     The setting WooCommerce->Settings->"Number of decimals" should only be used as a display option and not the way it is right now where it's also used for internal calculations.
> 
>     Don't round any data that's used for internal calculations. This will keep the precision as high as possible.
> 
>     Don't round any data that's getting stored to the database. This will maintain a high precision.
> 


I have tried to go with this approach in the past, and this is not the first we have been requested to follow this approach. However, the problem here is, we always display rounded values to the customer, which means that if we use high precision values in the backend, it will mismatch with what is shown to the customer. 

For egs, if a customer were to see the tax breakup of individual items, they will frequently not add up to final total amount because we would be showing rounded values on the frontend but would be using high precision values on the backend.

Current errors and discrepancies are mostly around using slightly different logic in different places. We are refactoring them to be in one place so that we get very consistent in how and when we round values.

I still have couple more fixes in works that would be available in a later version and close the remaining gaps.

I am closing this issue so that we can focus on individual issues linked here. However, feel free to comment back if you want to further discuss and I will re-open this.

**Comment by larssn** [comment]
The suggested approach would still work, I think it mainly depends on how aggressively you do your rounding. We've used the above approach in a Point of Sale app, which contains all the same concepts such as orders, tax, products, analytics etc., and there that approach worked fine.

I'll draw it to better get my point across:
```
------------------------------------------------------------------------
|         Presentation layer (your views and JS)                       |
|         All views would have access to unrounded -                   |
|         data, coming from the Application layer, and -               |
|         it is the view's responsibility to round the numbers.        |
------------------------------------------------------------------------
|         Application layer                                            |
|         Strive to not have a single line of rounding anywhere.       |
|         All your math happens here.                                  |
------------------------------------------------------------------------
|         Data layer (probably your data stores)                       |
|         Since rounding errors are usually at the 14th -              |
|         decimal place, it's safe to do a round that kills off -      |
|         that value, or the 13th to be safe.                          |
|         This will maintain high precision.                           |
------------------------------------------------------------------------
```
WC's current approach to rounding seems completely out of control: you have hundreds of lines of code of various rounding functions, that I can only imagine will confuse even your developers. Several files has their own flavour of rounding: some use `round()`, some use various custom functions, some use filters, some places the decimals are hardcoded, some not. It's begging for a refactor tbh, which I would strongly recommend you do, lest the [Lava flow](https://en.wikipedia.org/wiki/Lava_flow_(programming)) anti-pattern becomes a reality, if it's not already, where no single dev dares touch any of it.

Our system has 4 lines of code dedicated to rounding (Dart code):

```
double roundTo(num value, {int decimals = 12}) {
  final precision = pow(10, decimals);

  return (value * precision).round() / precision;
}
```

Here's a php version:
```
/**
 * Rounds to 13 significant numbers
 *
 * @param float $num The number to round.
 * @param int $precision The amount of significant digits to keep.
 * @return num The number.
 */
private function round_to( $num, $precision = 13 ) {
	$precision = pow( 10, $precision );
	return round( $num * $precision ) / $precision;
}
```

> For egs, if a customer were to see the tax breakup of individual items, they will frequently not add up to final total amount because we would be showing rounded values on the frontend but would be using high precision values on the backend.

It sounds like you have too much business logic in your presentation layer. The frontend should just get the values from the backend, and not try to do clever math. It should only **present** the data, and the only thing it should be allowed to do is round it, so it's pleasing to the eye.

**Comment by vedanshujain** [comment]
@larssn Thanks for posting this comment, It looks like what are you suggesting is quite similar to what we are moving towards. Currently, the focus is to consolidate rounding operations at one place so that each file don't have their own flavor of rounding.
I don't think that we will completely move to a pattern like you suggest, however centralizing rounding operations should provide us most of the benefits of that pattern. 

>  It's begging for a refactor tbh, which I would strongly recommend you do, lest the Lava flow anti-pattern becomes a reality, if it's not already, where no single dev dares touch any of it.

A big refactor or start from scratch is always very tempting, however, I feel that we are in good shape already and with small improvements we should be able to make this more robust. 

Regarding storing high accuracy values instead of rounding off values I think we can take a call again when we are closer to have all the rounding in one place. As of now, it will create more problems than it will solve.

**Comment by marekka** [comment]
Hi, I'm still having this problem for the delivery so it's rounding to either 9.98 or 10 :(

It's rounded correctly however on products, so if entered 8.3265 for product, the price displayed is 9.99

If entered 8.3265 for shipping it's 9.98

**Comment by skullo27** [comment]
> Hi, I'm still having this problem for the delivery so it's rounding to either 9.98 or 10 :(
> 
> It's rounded correctly however on products, so if entered 8.3265 for product, the price displayed is 9.99
> 
> If entered 8.3265 for shipping it's 9.98

We have this exact same issue. If we enter shipping including tax at £9.99 it shows as £10.00. If we enter excluding tax at £8.325 it is the same £10.00. If we enter anything below 8.325, e.g. 8.324 it displays as £9.98 so you cannot get the value for shipping at £9.99!

Note:
- Tax is set to 20.0000%
- We have it set to round at product level (neither setting here makes a difference, however)
- Decimal places is set to 2.

It does seem like Woo cannot perform basic maths. 8.325 x 1.2 = 9.99 (or 8.325 + 20% = 9.99), **not 10.00**. 

It seems crazy that such a widely distributed platform as WP/WC cannot do basic maths. I understand there can be under the hood reasons for this, but really that needs to be fixed as users should not have to care about such things.

Furthermore, before marekka commented about this in Oct 2021 the last chat about this was in 2019 and version 3.9 for fixes... we are now at version 5.9 with 6.0 having just come out and no sign of a fix!

Is there at the very least a workaround until you fix this?

**Comment by peterfabian** [comment]
Hi folks, apologies for the trouble. Regarding rounding of shipping and applying tax or not: this is a [known limitation](https://github.com/woocommerce/woocommerce/wiki/How-Taxes-Work-in-WooCommerce#defining-prices). Please upvote the [enhancement request](https://github.com/woocommerce/woocommerce/issues/27611) if you'd like to see this fixed.

**Comment by StaniKub** [comment]
> Is there at the very least a workaround until you fix this?

There is a workaround based on this post: https://annaschneider.me/blog/calculate-shipping-cost-including-tax-woocommerce/

The basic calculation is:
Shipping cost / 1.Taxrate 

If the hipping cost is 3,95€ and the tax rate is 21% this means:
3.95 / 1.21

These calculations can just be added in the shipping cost instead of the usual price.
