### ISSUE TITLE
Variable product prices are cached with the wrong tax amount

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#25255]
**Describe the bug**
WooCommerce uses transients to store prices for variable products. It uses a hash for this so it can be unique per tax rate. However the status of a customer being tax exempt is not included in this hash. This allows us to cache incorrect values and show customer products exclusive of tax when they should be seeing products inclusive of tax.

I initially reported this for the [EU VAT Number](https://woocommerce.com/products/eu-vat-number/) extension. However since there are multiple plugins which can set a customer as tax exempt it would be better to fix this in core.

WooCommerce provides the filter `woocommerce_get_variation_prices_hash` we can use with the following note:

> Create unique cache key based on the tax location (affects displayed/cached prices), product version and active price filters. DEVELOPERS should filter this hash if offering conditional pricing to keep it unique.

**To Reproduce**
1. Setup a variable product with taxes
2. Set prices in the store to show including taxes
3. Set up taxes for the site, it's the easiest to reproduce with just one tax rate for every location
4. Use one logged in user and save a location as well as a matching VAT number in their account
5. View the shop page and you should now see the variable product with no tax (user is tax exempt)
6. In an incognito window view the same shop page and notice that the variable product is still showing without taxes
7. Clear the transients in WooCommerce > Status > Tools
8. Refresh the incognito window and see the variable product including taxes
9. Now refresh the shop page again for the logged in user and the variable product shows including taxes (we would expect it to show excluding taxes)

**Expected behavior**
I would expect the customers to always see the products with the right tax rate. Regardless of whether they are tax exempt or not.

To make the hash unique I used the following snippet:

```
add_filter(
	'woocommerce_get_variation_prices_hash',
	function ( $price_hash ) {
		if ( WC()->customer->get_is_vat_exempt() ) {
			$price_hash['is_vat_exempt'] = true;
		}
		return $price_hash;
	}
);
```

After activating the snippet and retesting, the variable products are shown with the correct prices.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only the extension is active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

```
WordPress 5.3
WooCommerce 3.8.1
WooCommerce EU VAT Number 2.3.16
```
</details>

Affected ticket: 2527197-zen

**Comment by juliaamosova** [comment]
Hi @mikkamp,

Thanks for opening the issue! I can reproduce it on my end. 

Documenting my steps below:

0. Testing on a brand new Jurassic Ninja install.

1. Setup a variable product with taxes:

Done:

![1](https://user-images.githubusercontent.com/19143190/71412335-2eeb6880-2645-11ea-9aed-2cb077657e6c.jpg)

2. Set prices in the store to show including taxes:

Done:

![2](https://user-images.githubusercontent.com/19143190/71412393-62c68e00-2645-11ea-8cd3-6cc8f30c3152.jpg)

3. Set up taxes for the site, it's the easiest to reproduce with just one tax rate for every location:

Done:

![tax](https://user-images.githubusercontent.com/19143190/71412888-8985c400-2647-11ea-8937-9f337f9ac8b8.jpg)

4. Use one logged in user and save a location as well as a matching VAT number in their account:

- I installed [EU VAT Number](https://woocommerce.com/products/eu-vat-number/) extension;
- I used one of the test VAT Numbers from the [EU VAT Number Test Data](https://www.braemoor.co.uk/software/vattest.php). In particular, I used a valid Austrian VAT Number `ATU66889218`;
- Next, I placed an order using this VAT number so the address and VAT number will be saved for the user and also to see if the VAT number is valid indeed:

Before applying the VAT number:

![before_vat](https://user-images.githubusercontent.com/19143190/71412948-ebdec480-2647-11ea-8041-02adf9546294.jpg)

After applying the VAT number:

![4](https://user-images.githubusercontent.com/19143190/71412952-f13c0f00-2647-11ea-8f11-3ae4945c4ec1.jpg)

Order placed:

![5](https://user-images.githubusercontent.com/19143190/71412998-29435200-2648-11ea-8419-55727bd52fa6.jpg)

5. View the shop page and you should now see the variable product with no tax (user is tax exempt):

Correct, I can see that:

![6](https://user-images.githubusercontent.com/19143190/71413112-9951d800-2648-11ea-8be3-bdfd11970348.jpg)

6. In an incognito window view the same shop page and notice that the variable product is still showing without taxes:

Indeed, I can see that:

![7](https://user-images.githubusercontent.com/19143190/71413294-665c1400-2649-11ea-9fed-6c82da6b4527.jpg)

8. Clear the transients in WooCommerce > Status > Tools:

Done:

![10](https://user-images.githubusercontent.com/19143190/71413392-e5514c80-2649-11ea-9270-dd5bd8c0a30d.jpg)

9. Now refresh the shop page again for the logged in user and the variable product shows including taxes (we would expect it to show excluding taxes):

Confirm that I can see that:

![11](https://user-images.githubusercontent.com/19143190/71413470-3bbe8b00-264a-11ea-8f71-fa3f797eb635.jpg)

I further tested with the snippet provided:

![12](https://user-images.githubusercontent.com/19143190/71413664-28f88600-264b-11ea-841e-58cdbbadd836.jpg)

And can confirm, that after applying the snippet, the tax rate is applied as expected - regardless of whether the customer is tax-exempt or not:

![13](https://user-images.githubusercontent.com/19143190/71413692-4b8a9f00-264b-11ea-9624-1d3cf7c094ad.jpg)

**Comment by vinod41** [comment]
Is any fix released?
I've exact same issue with variable product and simple product both. Tax not getting calculated. Strange but Sometimes Tax value get double reduced.
eg: price entered at backend including tax price is 299 INR, Tax rate 18% set in variable product.
Shop displays : 253.39 (before tax) and other similar product 214.74. (double tax reduced)
At the backed price was entered 299.

Tax structure
same state billing: CGST 9% + SGST 9% (had to show breakup) (total 18%)
billing to other state: IGST 18%

I'm using currency switcher plugin, which is working fine.
I've tried disabling plugins, but no change.
Only when logged in user or in checkout page when address is entered, tax shows up correctly.
set Tax based on Customer Geolocate.
I've Cleared the transients in WooCommerce > Status > Tools but no change.
I've applied the snippet above to test, but no change.

I've same settings 
![image](https://user-images.githubusercontent.com/16012915/75581598-d6df4100-5a8f-11ea-920f-dca597773fb5.png)

![image](https://user-images.githubusercontent.com/16012915/75581743-202f9080-5a90-11ea-94cb-3c91a83a6991.png)

**Comment by vinod41** [comment]
Hi,
I've figured it out. I'ts not a bug or probably is a bug??
I've add additional Row for Country with State code *
IN - *- *-*-Tax rate and set priority accordingly.

So, without adding This additional row Tax won't display in front although I'v defined all states in the Tax rates.

**Comment by jaylinski** [comment]
@mikkamp Thank you so much for the bugfix snippet. :medal_sports:  I can confirm this fixes the issue.

**Comment by apmwebdev** [comment]
I'm running into this issue now, but it appears to be happening with all taxes, not just VAT. If you have taxes entered inclusive of tax and displayed inclusive of tax, the prices for variable products will be displayed exclusive of tax on the product and cart pages until you go to checkout. The snippet provided does not fix the issue unless you're using the EU VAT plugin. I also tried the work-around suggested by @vinod41, but that didn't help either. 3507099-zen is the ticket in question. Any chance that there is a work-around for sites not using the VAT plugin?

**Comment by roykho** [comment]
So I had a look at this and I think it is important to first establish what is the intended design/behavior before we know how to assess this issue.

From what I am seeing (and correct me if I am wrong), WC core does not have any concept of tax exemption that is tied to the logged in customer saved. This means tax exemption only happens via filters dynamically. So without outside 3rd party plugins, WC core is working correctly as designed.

Now enter a 3rd party plugin like the EU VAT Numbers that manipulates the VAT exemption. From what I gathered according to the OP, a customer that once had an order with VAT exemption, they should see products with no VAT applied. It would seem this is a behavior that a 3rd party wants to change and perhaps would be better suited to be added in the 3rd party plugin?

If you're able to reproduce this issue with just WC Core, please provide the steps and we'll look into this again. I will keep this open for now.

**Comment by mikkamp** [comment]
> WC core does not have any concept of tax exemption that is tied to the logged in customer saved.

I do agree that WC core by itself, doesn't allow you to set this value for a customer. However the status `is_vat_exempt` is stored in the `WC_Customer` class and if we search for the usage of the function `get_is_vat_exempt` then we can see quite a few locations where WC core acts differently depending on whether the customer is exempt or not.

My interpretation would be that WC core should be consistent in how it handles a customer that is VAT exempt and always take it into consideration when presenting data.

**Comment by juliaamosova** [comment]
I am bumping the priority of this issue from `low` to `high`. According to the comments on this issue, many merchants could be affected. There also seems to be a similar issue reported here: https://github.com/woocommerce/woocommerce/issues/29888.

**Comment by masahrpro** [comment]
> I am bumping the priority of this issue from `low` to `high`. According to the comments on this issue, many merchants could be affected. There also seems to be a similar issue reported here: #29888.

Hoping for a quick fix for this! Our client is really suffering with this problem.

**Comment by sebastianvdn** [comment]
I'm also having this issue

So for example, let’s say I’ve got a variable product:
Color 1 – Grey – 19.99 (excl tax) – 24.19 (incl tax)
Color 2 – Green – 19.99 (excl tax) – 24.19 (incl tax)

This price should be shown on the product page.

Now the issue is that on the product page it show 29.27, which is an additional tax on the 24.19, its, calculating double tax.

Please I need a fix for this ASAP, thank you.

Sebastian

**Comment by masahrpro** [comment]
@jonathansadowski @juliaamosova Any updates on this issue?

**Comment by isaaclubow** [comment]
I believe I'm experiencing the same problem. Any u pdates?

**Comment by masahrpro** [comment]
@jonathansadowski  @juliaamosova This has taken a long time despite the "High" priority set to this task.  Any updates on this issue?

**Comment by masahrpro** [comment]
Still waiting for any updates on this issue.

**Comment by masahrpro** [comment]
We have updated to the latest release where this was marked as fixed, but the problem still exist. Seeing VAT 0% prices again. @barryhughes @jeffstieler

**Comment by jeffstieler** [comment]
@masahrpro can you please open a [New Issue](https://github.com/woocommerce/woocommerce/issues/new/choose) with steps to reproduce?

Thank you!
