### ISSUE TITLE
Add product: Product-list is empty if there are too many variable products

### ISSUE THREAD

**Issue by TCHessen** [woocommerce/woocommerce#28722]
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

Describe the bug

In the backend I try to add a product to an order. I use a search term that matches on many variable-products and many variations. If there are more than 30 variable-products that matches the search-term, an empty result is shown.

Expected behavior

I'd expect that I get up to 30 results of the variations.

Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)

Not so easy, because it depends on the product names and used database. I could provide a video of the two behaviors with and without the workaround.

Workaround (crappy):

in /wp-content/plugins/woocommerce/includes/class-wc-ajax.php change line 1573 from

$ids        = $data_store->search_products( $term, '', (bool) $include_variations, false, $limit, $include_ids, $exclude_ids );
to 
$ids        = $data_store->search_products( $term, '', (bool) $include_variations, false, $limit+100, $include_ids, $exclude_ids );

WordPress Environment:

Wordpress: 5.6
Woocommerce: 4.8.0

**Comment by juliaamosova** [comment]
Hi @TCHessen,

Thank you for reporting the issue! It seems similar to https://github.com/woocommerce/woocommerce/issues/28722. We will investigate it further and will provide a proper answer after.

**Comment by TCHessen** [comment]
Ok, I see. If it helps I'd make a video or would make a websession to show you the issue.

**Comment by tammullen** [comment]
Hi @TCHessen 

There is known issue reported earlier in https://github.com/woocommerce/woocommerce/issues/28417 and fixed in https://github.com/woocommerce/woocommerce/pull/28468 which causes no results to appear when searching for products in the add product modal. The fix will be included in WooCommerce 4.9.0.

This might be what is causing the behaviour you are seeing although it sounds like you are only seeing no search results for the case of when you know there is greater than 30 variations that match your search term? Can you confirm you do see search results in other cases?

To test the scenario you described I set up some variable products with 50 variations each. I then searched for a term I knew would match >100 variations. I was able to see results returned as expected (albeit just the first 28 in this example) 
![Screenshot 2021-01-11 at 22 23 06](https://user-images.githubusercontent.com/24649833/104245153-a7dd7e00-545b-11eb-9498-24a00873222b.png)

It will be great if you could share your current System Status Report. You can get it by navigating to the WooCommerce / Status section of your site. Once there, click on the Get system report button and then copy it by clicking on the Copy for support button. Then paste it here in a comment.

In addition to that, please confirm if you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by TCHessen** [comment]
I tested everything without any other plugins.

I think that the other problems are not compareable to mine. Here you can see two queries createted within the search_product method and their results. I added post_type to show the problem and changed limit to 130 (normally 30).

What you can see is that the first query returns more than 30 rows with post_type=="product". So normally with a limit of 30 no result with post_type="product_variation" are returned. The problem is that this depends on the random order of the query result if no specific ORDER-clause is given.

Maybe the correct fix would be an ORDER-clause like

ORDER BY posts.post_type DESC, posts.post_parent ASC, posts.post_title ASC

Here are the results of the queries:

Search for "Angel":
```
SELECT DISTINCT posts.ID as product_id, posts.post_parent as parent_id, posts.post_type FROM wp_2_posts posts
LEFT JOIN wp_2_wc_product_meta_lookup wc_product_meta_lookup ON posts.ID = wc_product_meta_lookup.product_id
LEFT JOIN wp_2_wc_product_meta_lookup parent_wc_product_meta_lookup
ON posts.post_type = 'product_variation' AND parent_wc_product_meta_lookup.product_id = posts.post_parent 
WHERE posts.post_type IN ('product','product_variation')
AND (  ( ( posts.post_title LIKE '%Angel%') OR ( posts.post_excerpt LIKE '%Angel%') OR ( posts.post_content LIKE '%Angel%' ) OR ( wc_product_meta_lookup.sku LIKE '%Angel%' )  OR ( wc_product_meta_lookup.sku = "" AND parent_wc_product_meta_lookup.sku LIKE '%Angel%' ) )) 
AND posts.post_status IN ('private','publish') 
ORDER BY posts.post_parent ASC, posts.post_title ASC
LIMIT 130

Result:

product_id | parent_id | post_type |  
-- | -- | -- | --
11344 | 0 | product
977 | 0 | product
39242 | 0 | product
39245 | 0 | product
24842 | 0 | product
1076 | 0 | product
1022 | 0 | product
836 | 0 | product
39236 | 0 | product
39239 | 0 | product
973 | 0 | product
1304 | 0 | product
1777 | 0 | product
35510 | 0 | product
30864 | 0 | product
1081 | 0 | product
1158 | 0 | product
1152 | 0 | product
39248 | 0 | product
39253 | 0 | product
33163 | 0 | product
35396 | 0 | product
17838 | 0 | product
38038 | 0 | product
38051 | 0 | product
34224 | 0 | product
39258 | 0 | product
116 | 0 | product
35859 | 0 | product
35798 | 0 | product
1581 | 0 | product
39217 | 0 | product
986 | 836 | product_variation
1156 | 973 | product_variation
[...]

```

Search for "Nukka": (same query as above, just change the search string)
```

product_id | parent_id | post_type |  
-- | -- | -- | --
39196 | 0 | product
39200 | 0 | product
17838 | 0 | product
38051 | 0 | product
34224 | 0 | product
39258 | 0 | product
116 | 0 | product
35859 | 0 | product
35798 | 0 | product
1581 | 0 | product
39217 | 0 | product
752 | 116 | product_variation
1582 | 1581 | product_variation
17839 | 17838 | product_variation
34225 | 34224 | product_variation
35799 | 35798 | product_variation
35860 | 35859 | product_variation
38052 | 38051 | product_variation
39218 | 39217 | product_variation
39259 | 39258 | product_variation
39289 | 39258 | product_variation
```

`
### WordPress Environment ###

WordPress address (URL): https://www.snowpaws.de/shop
Site address (URL): https://www.snowpaws.de/shop
WC Version: 4.8.0
REST API Version: ✔ 4.8.0
WC Blocks Version: ✔ 4.2.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.7.3
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: ✔
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: nginx/1.19.6
PHP Version: 7.4.13
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1i

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.27-MariaDB-0+deb10u1-log
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.8.0
WC Database Prefix: wp_2_
Datenbank-Gesamtgröße: 71.94MB
Datenbank-Datengröße: 38.67MB
Datenbank-Indexgröße: 33.27MB
wp_2_woocommerce_sessions: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_2_woocommerce_order_items: Daten: 0.30MB + Index: 0.14MB + Engine InnoDB
wp_2_woocommerce_order_itemmeta: Daten: 3.52MB + Index: 4.03MB + Engine InnoDB
wp_2_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_2_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_actionscheduler_actions: Daten: 1.52MB + Index: 0.69MB + Engine InnoDB
wp_2_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_actionscheduler_logs: Daten: 0.50MB + Index: 0.41MB + Engine InnoDB
wp_2_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_comments: Daten: 1.52MB + Index: 1.13MB + Engine InnoDB
wp_2_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_ngg_album: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_ngg_gallery: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_ngg_pictures: Daten: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_2_options: Daten: 1.52MB + Index: 0.38MB + Engine InnoDB
wp_2_postmeta: Daten: 11.52MB + Index: 13.03MB + Engine InnoDB
wp_2_posts: Daten: 2.52MB + Index: 0.94MB + Engine InnoDB
wp_2_storeabill_documentmeta: Daten: 3.52MB + Index: 4.03MB + Engine InnoDB
wp_2_storeabill_documents: Daten: 0.34MB + Index: 0.31MB + Engine InnoDB
wp_2_storeabill_document_itemmeta: Daten: 5.52MB + Index: 4.03MB + Engine InnoDB
wp_2_storeabill_document_items: Daten: 1.52MB + Index: 0.47MB + Engine InnoDB
wp_2_storeabill_document_noticemeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_storeabill_document_notices: Daten: 0.23MB + Index: 0.08MB + Engine InnoDB
wp_2_storeabill_journals: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_termmeta: Daten: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_2_terms: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_2_term_relationships: Daten: 0.23MB + Index: 0.19MB + Engine InnoDB
wp_2_term_taxonomy: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_admin_notes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wc_customer_lookup: Daten: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_2_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_order_product_lookup: Daten: 0.25MB + Index: 0.31MB + Engine InnoDB
wp_2_wc_order_stats: Daten: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_2_wc_order_tax_lookup: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_product_meta_lookup: Daten: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_2_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_gzd_dhl_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_gzd_dhl_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_gzd_shipmentmeta: Daten: 0.47MB + Index: 0.33MB + Engine InnoDB
wp_2_woocommerce_gzd_shipments: Daten: 0.14MB + Index: 0.05MB + Engine InnoDB
wp_2_woocommerce_gzd_shipment_itemmeta: Daten: 0.16MB + Index: 0.16MB + Engine InnoDB
wp_2_woocommerce_gzd_shipment_items: Daten: 0.16MB + Index: 0.25MB + Engine InnoDB
wp_2_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wpmailsmtp_tasks_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wpmm_subscribers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_blogmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogs: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_registration_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_signups: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_site: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sitemeta: Daten: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Daten: 1.52MB + Index: 0.81MB + Engine InnoDB
wp_users: Daten: 0.06MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

attachment: 1914
custom_css: 1
customer_groups: 3
customize_changeset: 7
display_type: 7
document_template: 4
invoice: 1474
nav_menu_item: 49
ngg_album: 1
ngg_gallery: 2
ngg_pictures: 117
note: 1
oembed_cache: 2
page: 19
post: 3
product: 140
product_variation: 186
revision: 242
shop_coupon: 46
shop_order: 1025
shop_order_refund: 25
vtprd-rule: 1
wc_order_email: 3
wc_order_status: 14

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

AfterShip - WooCommerce Tracking: von AfterShip – 1.10.2 – Die installierte Version wurde nicht mit der aktiven WooCommerce-Version 4.0 getestet
B2B Market: von MarketPress – 1.0.6.3-support
PW WooCommerce Bulk Edit: von Pimwick
LLC – 2.83

Theme Customisations: von WooThemes – 1.0.0
WooCommerce Blöcke: von Automattic – 4.2.0
PayPal PLUS für WooCommerce: von Inpsyde GmbH – 2.2.1
Germanized für WooCommerce Pro: von vendidero – 3.1.2
Germanized für WooCommerce: von vendidero – 3.3.4
WooCommerce Order Status Manager: von SkyVerge – 1.11.9
WooCommerce: von Automattic – 4.8.0
WP Dashboard Notes: von Jeroen Sormani – 1.0.10
NextGEN Gallery: von Imagely – 3.5.0
NextGEN Gallery: von Imagely – 3.5.0
WP Maintenance Mode: von Designmodo – 2.3.0
Vendidero Helper: von Vendidero – 1.3.0
Gutentor - Gutenberg Blocks - Page Builder for Gutenberg Editor: von Gutentor – 3.0.2
Geolocation IP Detection: von Yellow Tree (Benjamin Pick) – 3.3.0
WP Mail SMTP: von WPForms – 2.5.1
SEOPress: von SEOPress – 4.2.1
Limit Login Attempts Reloaded: von Limit Login Attempts Reloaded – 2.19.0

### Inactive Plugins (6) ###

Akismet Anti-Spam: von Automattic – 4.1.8
Free & Simple Contact Form Plugin - Pirateforms: von WPForms – 2.5.2
Query Monitor: von John Blackbourn – 3.6.5
Simple Lightbox Gallery - Responsive Lightbox Gallery: von Weblizar – 1.8.2
WooCommerce PayPal Checkout Gateway: von WooCommerce – 2.1.1
WPForms Lite: von WPForms – 1.6.4.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop-Basis: #1264 - /snowpaws-sleddog-equipment/
Warenkorb: #20 - /warenkorb/
Kasse: #21 - /kasse/
Mein Konto: #22 - /mein-konto/
Allgemeine Geschäftsbedingungen: #15 - /agb/

### Theme ###

Name: Storefront
Version: 3.1.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Abgeschlossen: 2.063
Oldest: 2020-12-13 17:05:34 +0100
Newest: 2021-01-12 00:31:13 +0100

Fehlgeschlagen: 5
Oldest: 2020-11-07 16:04:55 +0100
Newest: 2020-11-09 19:28:23 +0100

Ausstehend: 5
Oldest: 2021-01-12 01:31:13 +0100
Newest: 2021-01-14 14:26:12 +0100

`

**Comment by TCHessen** [comment]
Here is the status report:

`
### WordPress Environment ###

WordPress address (URL): https://www.snowpaws.de/shop
Site address (URL): https://www.snowpaws.de/shop
WC Version: 4.8.0
REST API Version: ✔ 4.8.0
WC Blocks Version: ✔ 4.2.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.7.3
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: ✔
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: nginx/1.19.6
PHP Version: 7.4.13
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1i

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.27-MariaDB-0+deb10u1-log
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.8.0
WC Database Prefix: wp_2_
Datenbank-Gesamtgröße: 71.94MB
Datenbank-Datengröße: 38.67MB
Datenbank-Indexgröße: 33.27MB
wp_2_woocommerce_sessions: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_2_woocommerce_order_items: Daten: 0.30MB + Index: 0.14MB + Engine InnoDB
wp_2_woocommerce_order_itemmeta: Daten: 3.52MB + Index: 4.03MB + Engine InnoDB
wp_2_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_2_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_actionscheduler_actions: Daten: 1.52MB + Index: 0.69MB + Engine InnoDB
wp_2_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_actionscheduler_logs: Daten: 0.50MB + Index: 0.41MB + Engine InnoDB
wp_2_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_comments: Daten: 1.52MB + Index: 1.13MB + Engine InnoDB
wp_2_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_ngg_album: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_ngg_gallery: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_ngg_pictures: Daten: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_2_options: Daten: 1.52MB + Index: 0.38MB + Engine InnoDB
wp_2_postmeta: Daten: 11.52MB + Index: 13.03MB + Engine InnoDB
wp_2_posts: Daten: 2.52MB + Index: 0.94MB + Engine InnoDB
wp_2_storeabill_documentmeta: Daten: 3.52MB + Index: 4.03MB + Engine InnoDB
wp_2_storeabill_documents: Daten: 0.34MB + Index: 0.31MB + Engine InnoDB
wp_2_storeabill_document_itemmeta: Daten: 5.52MB + Index: 4.03MB + Engine InnoDB
wp_2_storeabill_document_items: Daten: 1.52MB + Index: 0.47MB + Engine InnoDB
wp_2_storeabill_document_noticemeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_storeabill_document_notices: Daten: 0.23MB + Index: 0.08MB + Engine InnoDB
wp_2_storeabill_journals: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_termmeta: Daten: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_2_terms: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_2_term_relationships: Daten: 0.23MB + Index: 0.19MB + Engine InnoDB
wp_2_term_taxonomy: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_admin_notes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wc_customer_lookup: Daten: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_2_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_order_product_lookup: Daten: 0.25MB + Index: 0.31MB + Engine InnoDB
wp_2_wc_order_stats: Daten: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_2_wc_order_tax_lookup: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_2_wc_product_meta_lookup: Daten: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_2_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_gzd_dhl_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_gzd_dhl_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_woocommerce_gzd_shipmentmeta: Daten: 0.47MB + Index: 0.33MB + Engine InnoDB
wp_2_woocommerce_gzd_shipments: Daten: 0.14MB + Index: 0.05MB + Engine InnoDB
wp_2_woocommerce_gzd_shipment_itemmeta: Daten: 0.16MB + Index: 0.16MB + Engine InnoDB
wp_2_woocommerce_gzd_shipment_items: Daten: 0.16MB + Index: 0.25MB + Engine InnoDB
wp_2_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_wpmailsmtp_tasks_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_2_wpmm_subscribers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_blogmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogs: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_registration_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_signups: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_site: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sitemeta: Daten: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Daten: 1.52MB + Index: 0.81MB + Engine InnoDB
wp_users: Daten: 0.06MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

attachment: 1914
custom_css: 1
customer_groups: 3
customize_changeset: 7
display_type: 7
document_template: 4
invoice: 1474
nav_menu_item: 49
ngg_album: 1
ngg_gallery: 2
ngg_pictures: 117
note: 1
oembed_cache: 2
page: 19
post: 3
product: 140
product_variation: 186
revision: 242
shop_coupon: 46
shop_order: 1025
shop_order_refund: 25
vtprd-rule: 1
wc_order_email: 3
wc_order_status: 14

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

AfterShip - WooCommerce Tracking: von AfterShip – 1.10.2 – Die installierte Version wurde nicht mit der aktiven WooCommerce-Version 4.0 getestet
B2B Market: von MarketPress – 1.0.6.3-support
PW WooCommerce Bulk Edit: von Pimwick
LLC – 2.83

Theme Customisations: von WooThemes – 1.0.0
WooCommerce Blöcke: von Automattic – 4.2.0
PayPal PLUS für WooCommerce: von Inpsyde GmbH – 2.2.1
Germanized für WooCommerce Pro: von vendidero – 3.1.2
Germanized für WooCommerce: von vendidero – 3.3.4
WooCommerce Order Status Manager: von SkyVerge – 1.11.9
WooCommerce: von Automattic – 4.8.0
WP Dashboard Notes: von Jeroen Sormani – 1.0.10
NextGEN Gallery: von Imagely – 3.5.0
NextGEN Gallery: von Imagely – 3.5.0
WP Maintenance Mode: von Designmodo – 2.3.0
Vendidero Helper: von Vendidero – 1.3.0
Gutentor - Gutenberg Blocks - Page Builder for Gutenberg Editor: von Gutentor – 3.0.2
Geolocation IP Detection: von Yellow Tree (Benjamin Pick) – 3.3.0
WP Mail SMTP: von WPForms – 2.5.1
SEOPress: von SEOPress – 4.2.1
Limit Login Attempts Reloaded: von Limit Login Attempts Reloaded – 2.19.0

### Inactive Plugins (6) ###

Akismet Anti-Spam: von Automattic – 4.1.8
Free & Simple Contact Form Plugin - Pirateforms: von WPForms – 2.5.2
Query Monitor: von John Blackbourn – 3.6.5
Simple Lightbox Gallery - Responsive Lightbox Gallery: von Weblizar – 1.8.2
WooCommerce PayPal Checkout Gateway: von WooCommerce – 2.1.1
WPForms Lite: von WPForms – 1.6.4.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop-Basis: #1264 - /snowpaws-sleddog-equipment/
Warenkorb: #20 - /warenkorb/
Kasse: #21 - /kasse/
Mein Konto: #22 - /mein-konto/
Allgemeine Geschäftsbedingungen: #15 - /agb/

### Theme ###

Name: Storefront
Version: 3.1.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Abgeschlossen: 2.063
Oldest: 2020-12-13 17:05:34 +0100
Newest: 2021-01-12 00:31:13 +0100

Fehlgeschlagen: 5
Oldest: 2020-11-07 16:04:55 +0100
Newest: 2020-11-09 19:28:23 +0100

Ausstehend: 5
Oldest: 2021-01-12 01:31:13 +0100
Newest: 2021-01-14 14:26:12 +0100

`

**Comment by TCHessen** [comment]
If you want me to add a pull request, please let me know. I have tested the order clause change and it works perfectly.

**Comment by TCHessen** [comment]
Just to let you know, 4.9.0 does not fix the issue, but the modified order-clause still fixes it.

**Comment by CharlieMRS** [comment]
I came across this problem today. Search term 'hammer' isn't returning product titled 'hammer holster' because there are a ton of other products that mention the hammer holster in their post content. And the results aren't scored to sort by relevancy.

Why not remove the excerpt and content OR clauses from $term_group_query in WC_Product_Data_Store_CPT::search_products. Couldn't the admin be expected to search with terms included in the product titles? 

At the very least the sorting should be fixed if possible. Thank you!

**Comment by barryhughes** [comment]
We should certainly take steps to address this. Let's still keep #30915 open, but likely we can resolve both as part of the same overall effort. Marking high priority given the number of voices across both reports.

**Comment by flakas** [comment]
Hi @TCHessen - thanks for the report.

I know this has been open for a very long time, and I appreciate your patience. We're currently going through some older WooCommerce issues, identifying what still needs fixing, and tidying up what's already fixed or out of scope.

It looks like this is already covered by #30915, so I'm going to close this one as a duplicate and we'll keep everything tracked over there.

If that doesn't look like the same issue to you, let me know and we'll reopen and take another look.
