### ISSUE TITLE
Free shipping handling of minimum order rule changes when coupons added and prices are entered and displayed inclusive of tax

### ISSUE THREAD

**Issue by GeoJunkie** [woocommerce/woocommerce#28752]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When `Apply minimum order rule before coupon discount` is active and prices are entered inclusive of tax and displayed that way in cart and checkout, free shipping is applied based on the minimum order amount including tax. 

However, when a coupon is applied, it uses the pre-tax amount and free shipping is no longer available.

This was reported in 3616232-zen and confirmed on a test site.

**Expected behavior**
The rule should be consistently applied and allow free shipping on the product's actual entered price.

**Actual behavior**
Instead, the free shipping rule seems to shift before and after a coupon is applied. See screenshots below for an example.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to **WooCommerce > Settings > Tax**
2. Set **Prices entered with tax** to **Yes, I will enter prices inclusive of tax**
3. Set **Display prices during cart and checkout** to **Including tax**
3. Add a tax rate
3. Add Free shipping with a required minimum order amount
4. Check the **Apply minimum order rule before coupon discount** option for Free shipping
5. Add a physical product with a price inclusive of tax is above the minimum order amount, but the pre-tax amount is below the minimum order amount
6. Add a coupon that doesn't include free shipping
7. Add the product to the cart
8. Confirm free shipping is available
9. Add the coupon
10. Confirm free shipping is no longer available

**Screenshots**

For the test case, I found that this occurs when both **Yes, I will enter prices inclusive of tax** and **Display prices during cart and checkout - Including tax** are selected.

![](https://d.pr/i/M58AEQ+)
Image Link: https://d.pr/i/M58AEQ

Test tax rate:

![](https://d.pr/i/RW9nFm+)
Image Link: https://d.pr/i/RW9nFm

Free shipping settings, with a minimum order amount of $10:

![](https://d.pr/i/Rey4wT+)
Image Link: https://d.pr/i/Rey4wT

Test product that is $10:

![](https://d.pr/i/I7z84W+)
Image Link: https://d.pr/i/I7z84W

Without the coupon free shipping is available (note that the pre-tax amount is below the threshold ($10 - $.0.82 tax = $8.18):

![](https://d.pr/i/tyozeC+)
Image Link: https://d.pr/i/tyozeC

Once the coupon is applied free shipping is no longer available:

![](https://d.pr/i/VHNj10+)
Image Link: https://d.pr/i/VHNj10

If I change the tax settings to be entered/displayed exclusive of tax, free shipping is available before and after the coupon is applied:

![](https://d.pr/i/sGQXDd+)
Image Link: https://d.pr/i/sGQXDd

![](https://d.pr/i/2BGqEp+)
Image Link: https://d.pr/i/2BGqEp

![](https://d.pr/i/5wvXBj+)
Image Link: https://d.pr/i/5wvXBj

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://3616232zen.local
Site address (URL): https://3616232zen.local
WC Version: 4.8.0
REST API Version: ✔ 4.8.0
WC Blocks Version: ✔ 3.8.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.7.3
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.3.5
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.8.0
WC Database Prefix: wp_
Total Database Size: 4.07MB
Database Data Size: 2.57MB
Database Index Size: 1.50MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
elfinder_file: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
elfinder_trash: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
customize_changeset: 1
page: 8
post: 2
product: 19
product_variation: 7
revision: 5
shop_coupon: 1
shop_order: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

Query Monitor: by John Blackbourn – 3.6.5
Adjust Curl Options: by Mik – 1.1
Debug Bar Actions and Filters Addon: by Subharanjan – 1.5.4
Debug Bar Console: by koopersmith – 0.3
Debug Bar Constants: by Juliette Reinders Folmer – 2.0.0
Debug Bar Cron: by Zack Tollman
Helen Hou-Sandi – 0.1.2

Debug Bar List Script & Style Dependencies: by Per Soderlind – 1.1
Debug Bar Post Types: by Juliette Reinders Folmer – 2.0.0
Debug Bar Remote Requests: by Matthew Boynes – 0.1.2
Debug Bar Shortcodes: by Juliette Reinders Folmer – 2.0.3
Debug Bar Transients: by Dominik Schilling – 0.5
Debug Bar: by wordpressdotorg – 1.1.2
SQL Executioner: by Justin Watt – 1.4
WooCommerce Sandbox Gateway: by Mik – 1.2
WooCommerce: by Automattic – 4.8.0
WordPress Admin Style: by Frank Bültge – 1.5.6
WP CLI Login Command Server: by Evan Mattson – 1.2
WP Crontrol: by John Blackbourn & crontributors – 1.9.0
WP File Manager: by mndpsingh287 – 6.9

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #12 - /shop/
Cart: #13 - /cart/
Checkout: #14 - /checkout/
My account: #15 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.0.0 (update to version 3.1.0 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 4
Oldest: 2020-12-15 15:54:51 +0000
Newest: 2021-01-03 13:22:29 +0000

`
```
</details>

**Comment by fvdbgit** [comment]
Hi, when is this problem going to be fixed?

**Comment by tammullen** [comment]
Hi @GeoJunkie 

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 
​
As you noted, it appears that it happens when the pre tax amount is below the threshold Free Shipping is applied as long as the including tax amount is above the threshold but when this happens the `apply minimum order rule before coupon discount ` option is ignored if it enabled.
​
We’re going to solve this bug as soon as possible. Stay tuned for updates.

**Comment by fvdbgit** [comment]
Hi @tammullen 

Thank you for taking the time to solve this bug.
Is it going to be solved soon?
Because it creates big frustrations to my customers who have to pay more with a coupon code than without the coupon code because of this bug. 
So this bug prevents me for making new coupon codes.
Could you please solve the bug as soon as possible? It's a bug that is already present since a very long time.

Thank you very much for your help!

**Comment by jrick1229** [comment]
Also seen in: 28203510-hc

**Comment by s4mh4ll** [comment]
Any one have a work-around for this for the time being?

**Comment by michylee** [comment]
Hi. Same bug. 
WordPress 5.7
WooCommerce 5.1.0

I hope you can fix it soon please.
Many thanks.

**Comment by fvdbgit** [comment]
Dear @tammullen , dear @GeoJunkie ,

When is this bug going to be fixed?
The issue is already open since more than 3 months (and exists since longer).

Thank you very much in advance for your answer.

**Comment by michylee** [comment]
Hi!
I haven't installed WooCommerce 5.2.0 yet.

Could it be that they fixed the problem with this version?
Thank you all.

**Comment by fvdbgit** [comment]
Hi,

The issue is still not fixed in the 5.2.2 version of WooCommerce!
Please fix this issue in version 5.2.3, it's VERY URGENT!

Thank you in advance.

**Comment by michylee** [comment]
@fvdbgit hi!
I have WooCommerce 5.2.2 with WordPress 5.7.1 and now the bug seems fixed for me.
![Schermata 2021-04-30 alle 15 47 16](https://user-images.githubusercontent.com/33864049/116704444-b2506300-a9cb-11eb-9cc8-ddf9a5c0098c.png)

I have free shipping above 37€.
The amount of the order in the screenshot was €38.15 to which I applied the 10% discount.
And... the free shipping was correctly applied even though the order total is now €34.34.

**Comment by fvdbgit** [comment]
Hi @michylee ,

Thank you for your comment.
However, I also have WooCommerce 5.2.2 with WordPress 5.7.1 and the bug is not fixed for me.

![Bug not fixed](https://user-images.githubusercontent.com/77958221/116772614-90e58a80-aa50-11eb-9737-12ae84270a36.png)

I have free shipping above 79€.
The amount of the order in the screenshot was 79.90€ to which I applied the 10% discount.
And... the free shipping is not applied after the coupon code is added...

Did you do something special to make it work?
Do you have all your price including taxes?

Dear @GeoJunkie & @tammullen : could you please confirm if the bug is fixed in WooCommerce version 5.2.2. or not?
If it is fixed, why doesn't it work on my website and how can I make it work?

Thank you very much for your help.

**Comment by fvdbgit** [comment]
Hi  @tammullen , @GeoJunkie

Is the bug corrected in the new WooCommerce version 5.3.0 ?

Thank you very much.

**Comment by s4mh4ll** [comment]
@fvdbgit I can confirm, this is NOT fixed in the latest version.

**Comment by fvdbgit** [comment]
Hi @tammullen , @GeoJunkie

This bug is still not fixed in WooCommerce version 5.5.1...

The fix has been requested since the 7th of January so more than 6 months ago.

Could you please fix this issue in the next WooCommerce version?

Thank you very much in advance.

**Comment by SandroSNunes** [comment]
Hi guys,

the problem is in woocommerce/includes/shipping/free-shipping/class-wc-shipping-free-shipping.php - LINE 156

```

if ( WC()->cart->display_prices_including_tax()  ) {
    $total = $total - WC()->cart->get_discount_tax();
}

```

if you delete those 3 lines it works.

While the problem isn't fixed you can do something like:

```

add_filter( 'woocommerce_shipping_free_shipping_is_available', 'my_shipping_free_shipping_is_available', 10, 3 );
function hb_shipping_free_shipping_is_available( $is_available, $package, $obj ) {

	$has_coupon         = false;
	$has_met_min_amount = false;

	if ( in_array( $obj->requires, array( 'coupon', 'either', 'both' ), true ) ) {
		$coupons = WC()->cart->get_coupons();

		if ( $coupons ) {
			foreach ( $coupons as $code => $coupon ) {
				if ( $coupon->is_valid() && $coupon->get_free_shipping() ) {
					$has_coupon = true;
					break;
				}
			}
		}
	}

	if ( in_array( $obj->requires, array( 'min_amount', 'either', 'both' ), true ) ) {
		$total = WC()->cart->get_displayed_subtotal();

		// CHANGED: Comented the next 3 lines.
		//if ( WC()->cart->display_prices_including_tax()  ) {
		//	$total = $total - WC()->cart->get_discount_tax();
		//}

		if ( 'no' === $obj->ignore_discounts ) {
			$total = $total - WC()->cart->get_discount_total();
		}

		$total = NumberUtil::round( $total, wc_get_price_decimals() );

		if ( $total >= $obj->min_amount ) {
			$has_met_min_amount = true;
		}
	}

	switch ( $obj->requires ) {
		case 'min_amount':
			$is_available = $has_met_min_amount;
			break;
		case 'coupon':
			$is_available = $has_coupon;
			break;
		case 'both':
			$is_available = $has_met_min_amount && $has_coupon;
			break;
		case 'either':
			$is_available = $has_met_min_amount || $has_coupon;
			break;
		default:
			$is_available = true;
			break;
	}

	return $is_available;

}

```

I hope this helps anyone.

Cheers

**Comment by fvdbgit** [comment]
Hi @tammullen , @GeoJunkie

Now that @SandroSNunes (thank you very much!) identified where the problem is coming from (the problem is in woocommerce/includes/shipping/free-shipping/class-wc-shipping-free-shipping.php - LINE 156), could you please fix this in the next WooCommerce version?

Thank you very much in advance. It's urgent.

**Comment by fvdbgit** [comment]
Dear WooCommerce developers,

When are you going to solve this bug in WooCommerce?

The case is open since the 7th of January 2021 and nothing moves.

No one is assigned to this case.

How is that possible? The priority is supposed to be "High".

Thank you in advance for your action.

**Comment by Tofandel** [comment]
Issue still present in 5.9.0 on a clean woocommerce install, if it was reproduced already 10 months ago and priority is high this should be addressed ASAP

**Comment by phillipcornwell** [comment]
Another report in 4631808-zen

**Comment by nicholasjeberlin** [comment]
Reported in 34016152-hc

**Comment by fvdbgit** [comment]
The bug is still not fixed. Priority is high. Could you please fix this bug in the next WooCommerce version?

**Comment by mpskovvang** [comment]
I haven't done extensive tests, but the solution might be only subtracting discount tax when _Coupons discounts_ is disabled.

```PHP
if ('no' === $this->ignore_discounts) {
    $total = $total - WC()->cart->get_discount_total();

    if (WC()->cart->display_prices_including_tax()) {
        $total = $total - WC()->cart->get_discount_tax();
    }
}
```

https://github.com/woocommerce/woocommerce/blob/3611d4643791bad87a0d3e6e73e031bb80447417/plugins/woocommerce/includes/shipping/free-shipping/class-wc-shipping-free-shipping.php#L156-L162

**Comment by fritexvz** [comment]
I cannot figure out how to calculate "free shipping" after the taxes?

**Comment by fvdbgit** [comment]
Hi, the issue/bug has still not been fixed in WooCommerce 6.2.1.
Please solve this issue, PRIORITY IS HIIGH!

**Comment by fvdbgit** [comment]
Hi @tammullen , @GeoJunkie

Issue still not fixed in WooCommerce version 6.3.1.
Who is assigned to solve this bug?
Is there a WooCommerce developer working on it?
Do you need more information about the bug?
The priority is HIGH and the issue is openend since the 7th of January 2021!
It is not acceptable that the issue is still not fixed, it is a BIG BUG in WooCommerce and it makes clients angry!
It shouldn't be so complicated to solve it, several people also gave possible solutions to hep you.

Please take this issue seriously and solve it asap.

Thank you in advance.

**Comment by dannii-** [comment]
Version 6.4.1 and not fixed, we have alot of customers that are dependant that free shipping price is free after a certain amount.
The price should be free after 1000 kr/sek. But since the VAT price isnt calculated its not working.
![github_fix](https://user-images.githubusercontent.com/4616482/178938553-f825d42e-beb4-4f9b-acee-162418cd557f.png)

**Comment by fvdbgit** [comment]
Dear WooCommerce developers,

This issue is still not fixed in WooCommerce version 6.8.2.

When are you going to solve this problem?

**Comment by fvdbgit** [comment]
Dear WooCommerce developers,

The issue was fixed in a recent version of WooCommerce (I don't remember which version exactly, I think 6.9.0) but reappears in the last versions of WooCommerce!
What is happening?
Could you please reinstate the fix that you had put in place in the next version of WooCommerce ASAP?

**Comment by kaushikasomaiya** [comment]
5698092-zen

**Comment by kaushikasomaiya** [comment]
I think this is deliberately set here: https://github.com/woocommerce/woocommerce/blob/0b52411ff768279dc59bb5376255c584e797970c/plugins/woocommerce/includes/shipping/free-shipping/class-wc-shipping-free-shipping.php#L157

**Comment by anastas10s-afk** [comment]
5750303-zen

**Comment by sk117** [comment]
We are currently facing the same problem. Is this issue being fixed? We are using WC 4.7.1

**Comment by kubiqsk** [comment]
Can you just move these 3 lines into the condition below? ( `if ( 'no' === $this->ignore_discounts ) {` )

https://github.com/woocommerce/woocommerce/blob/4db856db05fe308e589a159a3cd6ea312ecc4acc/plugins/woocommerce/includes/shipping/free-shipping/class-wc-shipping-free-shipping.php#L156C2-L158

Now it will subtract that `get_discount_tax` from `$total` event when `$this->ignore_discounts` is `TRUE`, so the free shipping method is not available in many cases then... This bug is opened for 2 years now and you just need to move 3 lines of code 1 line down...

PLEASE DO IT!

Correct version will be
```php
if ( 'no' === $this->ignore_discounts ) {
	$total = $total - WC()->cart->get_discount_total();
	if ( WC()->cart->display_prices_including_tax() ) {
		$total = $total - WC()->cart->get_discount_tax();
	}
}
```
