### ISSUE TITLE
For Twenty Twenty One Dark mode theme, 'View cart' CTA  on ( label name ) disappears when user performs mouse over on CTA.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#28955]
## Bug Description:
For Twenty Twenty One Dark mode theme, 'View cart' CTA  on ( label name ) disappears when user performs mouse over on CTA.

## Environment:
Windows 10, macOS Mojave v10.14.6 (18G103)
Browser: Chrome(Version 87.0.4280.88 (64-bit))
                Firefox(Version 83.0)(64-bit)
                Safari: v13.1.1 (14609.2.9.1.3)

## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all the required plugins
1. Complete the Onboarding setup wizard.
1. Select Twenty Twenty One Theme and enable Dark mode.
1. Add some products.
1. Go to frontend and click on of the Product.
1. Click on "Add to Cart" button.
1. Note that "View Cart" button appears.
1. Now perform mouse over on View cart button.
1. Observe that 'View cart' CTA  label name disappears.

## Actual Result:
For Twenty Twenty One Dark mode theme, 'View cart' CTA  on ( label name ) disappears when user performs mouse over on CTA.

## Expected Result:
For Twenty Twenty One Dark mode theme, 'View cart' CTA  on ( label name ) should not get disappear when user performs mouse over on CTA.

## Video:

https://user-images.githubusercontent.com/41110392/106015640-af9c5400-60e4-11eb-8e71-053361b1ba6f.mp4

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @gglobalstep,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

Noting that dark mode needs to be enabled in both the theme and the OS/device:

![](http://g.recordit.co/THrp0QUc7C.gif)

Using Dark Mode is popular which is why I think we should fix this issue soonish.

**Comment by gglobalstep** [comment]
This issue is also observed for the "Apply Coupon" button on Checkout page. 
Please refer to the video below:

https://user-images.githubusercontent.com/41110392/110761390-b25a9f00-8275-11eb-921e-e46bad3e50da.mp4

**Comment by rrennick** [comment]
In WC 7.9-dev, a view cart button is added below the add product button. However, the issue with the checkout coupon button still exists.

<img width="955" alt="Screenshot 2023-06-19 at 4 36 24 PM" src="https://github.com/woocommerce/woocommerce/assets/343847/4158983e-37ba-4d78-b9f5-362745696ddd">

**Comment by rrennick** [comment]
This has been fixed.
