### ISSUE TITLE
Rounding difference on refunds vs order amount

### ISSUE THREAD

**Issue by neilmccreadie** [woocommerce/woocommerce#30263]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
AS per 4127203-zen
When refunding an order with two line items (in this case of the same price), the rounding is different on the total to what was applied to the original order / what showed in the cart. When switching to rounding based on Subtotal and placing the same order and then refunding, the totals are rounded correctly as per the cart total. 
I understand based on [this report](https://github.com/woocommerce/woocommerce/issues/30159), that there are differences expected between line item and subtotal, but one would then expect these to be the same on order total as on refund. 

**Expected behavior**
It's expected that the refund total would be the same as that of the original order. 

**Actual behavior**
If rounding is set as default, per line item, the order total for two separate items each priced at 2.10 shows as 4.20 in the cart and payment is captured as such. 
When same order is processed as a refund, the rounding is different and totals 4.21

Switching to rounding per Subtotal, the cart total still shows at 4.20 and when processing the refund, it's then also 4.20. 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Set tax rate to 24%
2. In Settings -> Tax, select: Yes, I will enter prices inclusive of tax
3. Leave Rounding unchecked, so it calculates per line.
4. Create two products priced at 2.10 each and add each to the cart.
5. Complete checkout and then mark order complete
6. Go to refund the order and you'll see that the refund amount is 4.21 and not 4.20 as per the order. 
7. Change Rounding to be checked on and replicate the steps above
8. You'll see now on refunding the new order that the total is 4.20, as per the order. 

**Screenshots**
2 Items ordered when rounding is set to be per line:
![https://d.pr/i/FMGKNe](https://d.pr/i/FMGKNe+) 
Full Size: https://d.pr/i/FMGKNe

Same order when refunding: 
![https://d.pr/i/wkf4yx](https://d.pr/i/wkf4yx+) 
Full Size: https://d.pr/i/wkf4yx

Changed rounding settings to Subtotal: 
![https://d.pr/i/PUpQR1](https://d.pr/i/PUpQR1+) 
Full Size: https://d.pr/i/PUpQR1

Same order when refunding: 
![https://d.pr/i/3M0F4l](https://d.pr/i/3M0F4l+) 
Full Size: https://d.pr/i/3M0F4l

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
### WordPress Environment ###

WordPress address (URL): https://woocgenqa001.northeurope.cloudapp.azure.com/etola_qa
Site address (URL): https://woocgenqa001.northeurope.cloudapp.azure.com/etola_qa
WC Version: 5.4.1
REST API Version: ✔ 5.4.1
WC Blocks Version: ✔ 5.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.3.1
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 4 Gt
WP Debug Mode: –
WP Cron: ✔
Language: fi
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.48 (Ubuntu)
PHP Version: 7.4.20
PHP Post Max Size: 8 Mt
PHP Time Limit: 120
PHP Max Input Vars: 10001
cURL Version: 7.58.0
OpenSSL/1.1.1i

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.48-MariaDB-0ubuntu0.18.04.1
Max Upload Size: 8 Mt
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.4.1
WC Database Prefix: wp_
Tietokannan kokonaiskoko: 21.76MB
Tietokannan tietojen koko: 15.24MB
Tietokannan hakemiston koko: 6.52MB
wp_woocommerce_sessions: Tiedot: 0.03MB + Indeksi: 0.02MB + Moottori InnoDB
wp_woocommerce_api_keys: Tiedot: 0.02MB + Indeksi: 0.03MB + Moottori InnoDB
wp_woocommerce_attribute_taxonomies: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_woocommerce_downloadable_product_permissions: Tiedot: 0.02MB + Indeksi: 0.06MB + Moottori InnoDB
wp_woocommerce_order_items: Tiedot: 0.09MB + Indeksi: 0.05MB + Moottori InnoDB
wp_woocommerce_order_itemmeta: Tiedot: 0.52MB + Indeksi: 0.52MB + Moottori InnoDB
wp_woocommerce_tax_rates: Tiedot: 0.02MB + Indeksi: 0.06MB + Moottori InnoDB
wp_woocommerce_tax_rate_locations: Tiedot: 0.02MB + Indeksi: 0.03MB + Moottori InnoDB
wp_woocommerce_shipping_zones: Tiedot: 0.02MB + Indeksi: 0.00MB + Moottori InnoDB
wp_woocommerce_shipping_zone_locations: Tiedot: 0.02MB + Indeksi: 0.03MB + Moottori InnoDB
wp_woocommerce_shipping_zone_methods: Tiedot: 0.02MB + Indeksi: 0.00MB + Moottori InnoDB
wp_woocommerce_payment_tokens: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_woocommerce_payment_tokenmeta: Tiedot: 0.02MB + Indeksi: 0.03MB + Moottori InnoDB
wp_woocommerce_log: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_actionscheduler_actions: Tiedot: 2.02MB + Indeksi: 0.45MB + Moottori InnoDB
wp_actionscheduler_claims: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_actionscheduler_groups: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_actionscheduler_logs: Tiedot: 0.38MB + Indeksi: 0.27MB + Moottori InnoDB
wp_commentmeta: Tiedot: 0.02MB + Indeksi: 0.03MB + Moottori InnoDB
wp_comments: Tiedot: 0.31MB + Indeksi: 0.30MB + Moottori InnoDB
wp_duplicator_pro_entities: Tiedot: 0.02MB + Indeksi: 0.11MB + Moottori InnoDB
wp_duplicator_pro_packages: Tiedot: 0.08MB + Indeksi: 0.02MB + Moottori InnoDB
wp_failed_jobs: Tiedot: 0.02MB + Indeksi: 0.00MB + Moottori InnoDB
wp_links: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_mailchimp_carts: Tiedot: 0.02MB + Indeksi: 0.00MB + Moottori InnoDB
wp_mailchimp_jobs: Tiedot: 0.08MB + Indeksi: 0.00MB + Moottori InnoDB
wp_maksuturva_queue: Tiedot: 0.14MB + Indeksi: 0.00MB + Moottori InnoDB
wp_maksuturva_status_query_log: Tiedot: 0.02MB + Indeksi: 0.00MB + Moottori InnoDB
wp_options: Tiedot: 3.02MB + Indeksi: 0.13MB + Moottori InnoDB
wp_paytrail_license: Tiedot: 0.02MB + Indeksi: 0.00MB + Moottori InnoDB
wp_postmeta: Tiedot: 3.19MB + Indeksi: 2.75MB + Moottori InnoDB
wp_posts: Tiedot: 3.36MB + Indeksi: 0.28MB + Moottori InnoDB
wp_queue: Tiedot: 0.02MB + Indeksi: 0.00MB + Moottori InnoDB
wp_social_users: Tiedot: 0.02MB + Indeksi: 0.03MB + Moottori InnoDB
wp_termmeta: Tiedot: 0.05MB + Indeksi: 0.03MB + Moottori InnoDB
wp_terms: Tiedot: 0.05MB + Indeksi: 0.03MB + Moottori InnoDB
wp_term_relationships: Tiedot: 0.08MB + Indeksi: 0.05MB + Moottori InnoDB
wp_term_taxonomy: Tiedot: 0.06MB + Indeksi: 0.03MB + Moottori InnoDB
wp_usermeta: Tiedot: 0.17MB + Indeksi: 0.06MB + Moottori InnoDB
wp_users: Tiedot: 0.02MB + Indeksi: 0.05MB + Moottori InnoDB
wp_verifone_order_process_status: Tiedot: 0.02MB + Indeksi: 0.00MB + Moottori InnoDB
wp_wc_admin_notes: Tiedot: 0.02MB + Indeksi: 0.00MB + Moottori InnoDB
wp_wc_admin_note_actions: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_wc_category_lookup: Tiedot: 0.02MB + Indeksi: 0.00MB + Moottori InnoDB
wp_wc_customer_lookup: Tiedot: 0.02MB + Indeksi: 0.03MB + Moottori InnoDB
wp_wc_download_log: Tiedot: 0.02MB + Indeksi: 0.03MB + Moottori InnoDB
wp_wc_order_coupon_lookup: Tiedot: 0.02MB + Indeksi: 0.03MB + Moottori InnoDB
wp_wc_order_product_lookup: Tiedot: 0.08MB + Indeksi: 0.06MB + Moottori InnoDB
wp_wc_order_stats: Tiedot: 0.05MB + Indeksi: 0.05MB + Moottori InnoDB
wp_wc_order_tax_lookup: Tiedot: 0.05MB + Indeksi: 0.03MB + Moottori InnoDB
wp_wc_product_meta_lookup: Tiedot: 0.09MB + Indeksi: 0.13MB + Moottori InnoDB
wp_wc_reserved_stock: Tiedot: 0.02MB + Indeksi: 0.00MB + Moottori InnoDB
wp_wc_tax_rate_classes: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_wc_webhooks: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_woos_search_trends: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_yith_wcwl: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_yith_wcwl_lists: Tiedot: 0.02MB + Indeksi: 0.05MB + Moottori InnoDB
wp_yoast_indexable: Tiedot: 0.34MB + Indeksi: 0.31MB + Moottori InnoDB
wp_yoast_indexable_hierarchy: Tiedot: 0.02MB + Indeksi: 0.05MB + Moottori InnoDB
wp_yoast_migrations: Tiedot: 0.02MB + Indeksi: 0.02MB + Moottori InnoDB
wp_yoast_primary_term: Tiedot: 0.02MB + Indeksi: 0.03MB + Moottori InnoDB
wp_yoast_seo_links: Tiedot: 0.05MB + Indeksi: 0.03MB + Moottori InnoDB
wp_yoast_seo_meta: Tiedot: 0.17MB + Indeksi: 0.00MB + Moottori InnoDB

### Post Type Counts ###

attachment: 316
blocks: 22
custom_css: 2
featured_item: 8
jetpack_migration: 2
nav_menu_item: 165
oembed_cache: 1
page: 108
post: 1
product: 345
product_variation: 44
revision: 1
shop_coupon: 4
shop_order: 245
shop_order_refund: 48
wcs_ruleset: 14
wpcf7_contact_form: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (27) ###

Contact Form 7 Extension For Mailchimp: -- Renzo Johnson – 0.5.41
Contact Form 7: -- Takayuki Miyoshi – 5.4
GDPR Cookie Consent: -- WebToffee – 2.0.1
Custom field finder: -- Team Yoast – 0.3
Disable REST API: -- Dave McHale – 1.6
Facebook for WooCommerce: -- Facebook – 2.4.0
Jetpack by WordPress.com: -- Automattic – 9.6.2
Loco Translate: -- Tim Whitlock – 2.5.2
Mailchimp for WooCommerce: -- Mailchimp – 2.5.1
Nextend Social Login: -- Nextendweb – 3.0.27
Solteq Etola Custom User Fields: --  –
Solteq New Order Status: --  – 1.4.1
WooCommerce Posti SmartShip: -- Lauri Karisola / markup.fi – 1.5.0
CTX Feed: -- WebAppick – 4.3.74
WooCommerce Noutopistehaku: -- Lauri Karisola / markup.fi – 1.2.0
WooCommerce Conditional Shipping Pro: -- Lauri Karisola / WooElements.com – 2.4.3
Woo Search Box: -- Guaven Labs – 2.1.13
Print Invoice & Delivery Notes for WooCommerce: -- Tyche Softwares – 4.6.2
WooCommerce Verifone Payment Gateway: -- Verifone Payment – 1.3.10
WooCommerce Measurement Price Calculator: -- SkyVerge – 3.18.0
WooCommerce: -- Automattic – 5.4.1
WooSidebars: -- WooCommerce – 1.4.5
Yoast SEO: -- Yoast -tiimi – 16.1.1
WP Crontrol: -- John Blackbourn & crontributors – 1.10.0
WP Rocket: -- WP Media – 3.8.8
WPS Hide Login: -- WPServeur
NicolasKulka
wpformation – 1.8.5

YITH WooCommerce Wishlist: -- YITH – 3.0.21

### Inactive Plugins (2) ###

Akismet Anti-Spam: -- Automattic – 4.1.9
YITH Color and Label Variations for WooCommerce: -- YITH – 1.10.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Kaupan polkutunnus: #77 - /shop/
Ostoskori: #76 - /cart/
Kassa: #75 - /checkout/
Oma tili: #74 - /my-account/
Tilaus- ja sopimusehdot: #1968 - /toimitusehdot/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.13.3
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product-cat.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome-child/woocommerce/myaccount/view-order.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php
flatsome/woocommerce/content-product_cat.php


### Action Scheduler ###

Valmis: 1 543
Oldest: 2021-06-08 12:35:00 +0300
Newest: 2021-07-09 11:07:52 +0300

Odottaa: 2
Oldest: 2021-07-09 12:07:52 +0300
Newest: 2021-07-09 12:07:52 +0300


### Status report information ###

Generated at: 2021-07-09 11:55:32 +03:00
```
</details>

**Comment by neilmccreadie** [comment]
I do see a similar issue here: https://github.com/woocommerce/woocommerce/issues/26734 but this was long since marked as solved in earlier releases.

**Comment by rodelgc** [comment]
Hi @neilmccreadie,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

I followed your steps exactly with the following settings:
- Tax rate = 24%
- Prices entered with tax =  YES
- Rounding = OFF (unchecked)
- 2 Products with price of $2.10 (incl. tax)
<img width="1603" alt="Screen Shot 2021-07-15 at 3 17 14 PM" src="https://user-images.githubusercontent.com/4509348/125749660-0c20fc0c-d4c8-4f8b-8dec-f6ad9375f3be.png">
<img width="675" alt="Screen Shot 2021-07-15 at 3 19 12 PM" src="https://user-images.githubusercontent.com/4509348/125749693-2af4efe9-31ce-4922-854d-334f2ddb8774.png">


And when I tried to do the refund, I get `$4.21` as the total refund amount even though the "Total refundable amount" says `$4.20`.
<img width="1306" alt="Screen Shot 2021-07-15 at 3 25 58 PM" src="https://user-images.githubusercontent.com/4509348/125749617-20d4c30c-684d-4761-8819-b420ff08e282.png">


Priority of this issue will be assigned shortly after we'd go through a round of prioritization. Please note it may take a couple of days.

**Comment by vedanshujain** [comment]
You are right that we should by default show whatever was actually charged, and recalculation should happen only when asked specifically. I am marking this as an enhancement request for now since this is how WC has worked for a long time instead of a bug.

**Comment by konstantin-designbox** [comment]
Any update on this?

I've got a customer who's having to manually round to 2 decimal places on the product totals when refunding... Please fix.

**Comment by raindeer** [comment]
This is still happening for me. 

![Image](https://github.com/user-attachments/assets/7801887f-aa1a-4261-8920-83c04777eb46)

What settings should you use to prevent this?
