### ISSUE TITLE
Attribute with same term used in product name not showing on cart and checkout

### ISSUE THREAD

**Issue by mpmedialab** [woocommerce/woocommerce#31422]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The attribute term "Black" of a variable product is not showing on the cart and checkout pages. The issue has been reported on this WooCommerce core forum thread https://wordpress.org/support/topic/woocommerce-product-variations-not-showing-on-orders/.

### Expected behavior

I'm expecting that the term "Black" would be displayed on the cart and checkout pages as other terms of the same variable product like "Antique White" and "White" are being shown.

### Actual behavior

When adding all variations to the cart I can only see on the cart and checkout pages the variations with attributes values "Antique White" and "White" but not the attribute with value "Black".

### Steps to reproduce

1. Go to WP dashboard > Products > Attributes 
2. Create Product attribute "Size" and assign value 16″ x 12″ for 12″ x 8″
3. Create Product attribute "Mount Colour" and assign values "Antique White", "Black", and "White"
4. Go to WP dashboard > Products > Add New
5. Add product name "VIENNA BLACK"
6. Select "Variable product" under Product data
7. Got to Product data > Attributes and add "Size" and "Mount Colour" attributes with their values - https://snipboard.io/JYEBVn.jpg
8. Go to Product data > Variations and create variations from all attributes - https://snipboard.io/Z6A0u1.jpg
9. Assign a regular price to the variations
10. Save and go to the product page in the frontend and add all variations to the cart - https://snipboard.io/lS3LqG.jpg
11.  View the cart page and the attribute "Mount Colour" with the value "Black" is not displayed while other values are - https://i.imgur.com/UIZZQue.png
12. Same happens in the checkout "Your order" section - https://i.imgur.com/238NzsJ.png

Additional info: If I change the product name to "VIENNA" then all attribute terms will be displayed.

### WordPress Environment

WordPress address (URL): 
Site address (URL): 
WC Version: 5.9.0
REST API Version: ✔ 5.9.0
WC Blocks Version: ✔ 6.1.0
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.8.0
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.4.1
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.67.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.9.0
WC Database Prefix: wp_
Total Database Size: 65.52MB
Database Data Size: 58.53MB
Database Index Size: 6.99MB
wp_woocommerce_sessions: Data: 0.17MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.31MB + Index: 0.33MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fakenames: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 38.09MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Data: 3.52MB + Index: 4.03MB + Engine InnoDB
wp_posts: Data: 2.50MB + Index: 0.56MB + Engine InnoDB
wp_prevent_direct_access_free: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_term_relationships: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.23MB + Index: 0.28MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.25MB + Index: 0.47MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 9.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 293
custom_css: 2
custom-css-js: 5
customize_changeset: 25
nav_menu_item: 5
page: 45
post: 3
product: 472
product_variation: 1985
revision: 238
shop_coupon: 3
shop_order: 394
shop_order_refund: 5
user_request: 3
wpforms: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 5.9.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /
Cart: #7 - /cart/
Checkout: #4027 - /checkout/
My account: #9 - /my-account/
Terms and conditions: #2915 - /terms-conditions-page/

### Theme ###

Name: Storefront Child Theme
Version: 1.0.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 3.9.1
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Canceled: 1
Oldest: 2021-11-24 02:11:55 +0000
Newest: 2021-11-24 02:11:55 +0000

Complete: 135
Oldest: 2021-11-11 01:02:17 +0000
Newest: 2021-12-11 15:57:48 +0000

Pending: 1
Oldest: 2021-12-12 13:44:48 +0000
Newest: 2021-12-12 13:44:48 +0000

### Status report information ###

Generated at: 2021-12-11 11:04:14 -05:00

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment]
Hi @mpmedialab ,


Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using WooCommerce 5.9.0 version. 

Please find below screenshots  for reference : 


Cart page : 

![#31422(cart)](https://user-images.githubusercontent.com/94531721/145980216-b74da6ec-2075-4362-a5ad-3c2aebf5e5db.jpg)

 Checkout page : 

![#31422(checkout)](https://user-images.githubusercontent.com/94531721/145980222-463501d3-0aa2-4895-86cf-114d664b2b91.jpg)

Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by K13NN13** [comment]
Hey Just curious if there is any update to this? Also having the same issue with product names that have the same name as an attribute.

**Comment by turpoint** [comment]
This is probably because of the following lines in `/woocommerce/includes/wc-template-functions.php` (line 3705). @kromeninja did you manage to fix it, or use a certain filter to bypass this behaviour?

```
// Check the nicename against the title.
if ( '' === $value || wc_is_attribute_in_product_name( $value, $cart_item['data']->get_name() ) ) {
    continue;
}
```

**Comment by K13NN13** [comment]
Hey @turpoint sadly I still have this issue, was hoping there would be some movement here on the issue 🤞

**Comment by turpoint** [comment]
@kromeninja not ideal, but I fixed it in my theme by using a filter and applying the same function as in the WC core, but without the lines that remove the attribute (I've put them in comments).

```
add_filter('woocommerce_get_item_data', function($item_data, $cart_item) {

	$item_data = [];

	if ( $cart_item['data']->is_type( 'variation' ) && is_array( $cart_item['variation'] ) ) {
		foreach ( $cart_item['variation'] as $name => $value ) {
			$taxonomy = wc_attribute_taxonomy_name( str_replace( 'attribute_pa_', '', urldecode( $name ) ) );

			if ( taxonomy_exists( $taxonomy ) ) {
				// If this is a term slug, get the term's nice name.
				$term = get_term_by( 'slug', $value, $taxonomy );
				if ( ! is_wp_error( $term ) && $term && $term->name ) {
					$value = $term->name;
				}
				$label = wc_attribute_label( $taxonomy );
			} else {
				// If this is a custom option slug, get the options name.
				$value = apply_filters( 'woocommerce_variation_option_name', $value, null, $taxonomy, $cart_item['data'] );
				$label = wc_attribute_label( str_replace( 'attribute_', '', $name ), $cart_item['data'] );
			}

			// Check the nicename against the title.
			// if ( '' === $value || wc_is_attribute_in_product_name( $value, $cart_item['data']->get_name() ) ) {
			// 	continue;
			// }

			$item_data[] = array(
				'key'   => $label,
				'value' => $value,
			);
		}
	}

	return $item_data;

}, 10, 2);
```

**Comment by K13NN13** [comment]
Hey @turpoint just used it and the variation is now showing up on the woocommerce basket and checkout, but not on the order complete emails or the woocommerce orders backend, its atleast better than it was, hopefully this can be resolved soonw without a workaround :) Appreciate it

**Comment by turpoint** [comment]
@kromeninja for the emails I used the filter below. For the backoffice I don't have the filter yet.

```
add_filter('woocommerce_display_item_meta', function($html, $item, $args) {
	$strings = array();
	$html    = '';
	$args    = wp_parse_args(
		$args,
		array(
			'before'       => '<ul class="wc-item-meta"><li>',
			'after'        => '</li></ul>',
			'separator'    => '</li><li>',
			'echo'         => true,
			'autop'        => false,
			'label_before' => '<strong class="wc-item-meta-label">',
			'label_after'  => ':</strong> ',
		)
	);

	foreach ( $item->get_formatted_meta_data('_', true) as $meta_id => $meta ) {
		$value     = $args['autop'] ? wp_kses_post( $meta->display_value ) : wp_kses_post( make_clickable( trim( $meta->display_value ) ) );
		$strings[] = $args['label_before'] . wp_kses_post( $meta->display_key ) . $args['label_after'] . $value;
	}

	if ( $strings ) {
		$html = $args['before'] . implode( $args['separator'], $strings ) . $args['after'];
	}

	return $html;
}, 10, 3);
```

**Comment by glynok** [comment]
Is there a fix for this problem?  I'm experiencing it on a client site.
![ScreenHunter 203](https://github.com/woocommerce/woocommerce/assets/148809209/fe0bc000-dc0e-47d1-8027-838fbe8f7bc4)

**Comment by glynok** [comment]
Further, if I duplicate the product it shows the missing size in the duplicate but it shows (copy) after the product description and if I remove this it reverts to not showing the size.

**Comment by scrobbleme** [comment]
+1 Just needed a couple of hours to identify this issue. This really should be fixed. This is not obvious.

There are a couple of places skipping items, if the attribute name is part of the variation title (which is always the case, as the title is generated from attribute values)

I think the feature, that attributes are skipped, should be removed entirely. 

I can't come up with a reason why to do it like this anyway. 
Beside it being very confusing.

Another workaround, at least from what I've seen in the usages.

```
add_filter( 'woocommerce_is_attribute_in_product_name','__return_false', PHP_INT_MAX, 3);
```

**Comment by pierorocca** [comment]
Hi @mpmedialab - thanks for the report.

I know this has been open for a very long time, and I appreciate your patience. We're currently going through some older WooCommerce issues, identifying what still needs fixing, and tidying up what's already fixed or out of scope.

I've taken a look and marked this ready for the engineering team to pick up.

What I'm seeing: The issue still exists on trunk. `wc_get_formatted_cart_item_data()` still skips variation attributes when the normalized attribute value is found in the variation product name. Cart, checkout, and mini-cart templates still render variation item details through this helper, so an attribute value such as `Black` can disappear when it is part of the generated product/variation name. The same underlying skip behavior also appears in formatted variation/order-meta paths. A June 2026 comment on the issue confirms users are still encountering this and names the same `woocommerce_is_attribute_in_product_name` workaround. No open PR references the issue.
